apps/www/src/content/components/alert-dialog.md
apps/www/src/content/components/hover-card.md
apps/www/src/content/components/radio-group.md

Fixes Radix links for `alert-dialog`, `hover-card`, and `radio-group`.
The lack of `-`'s may be an error on Radix's end since their route for `aspect-ratio` (https://www.radix-svelte.com/docs/aspect-ratio) seems to follow this convention. We can update this again once that's sorted on their end.

docs: fixed broken radix links

---

apps/www/src/lib/components/ui/form/FormField.svelte

The problem ("feature") is that the name attribute must be set to the schema field name. So in the case of arrays, the index isn't needed, though it's required for making it a formFieldProxy, so the id is used for that.
It's a problem with normal form posting only, with `dataType: 'json'` this isn't an issue, since the name attribute is irrelevant.

Temp fix for form field name attribute.

---

apps/www/src/lib/components/docs/examples/hover-card/HoverCardDemo.svelte

Fix for #86 issue
- Removed `Button` component
- Added tailwind classes for the `HoverCardTrigger` component
- Added link attributes - `href`, `target`, `rel`

fix: hover card focus with tab key

---

apps/www/src/lib/components/ui/dialog/DialogPortal.svelte

Closes: #77 
Remove unused props from dialog portal component.

fix: remove unused props from dialog portal

---

apps/www/src/lib/components/docs/examples/dialog/DialogDemo.svelte

Closes: #79 
`DialogTrigger` already renders a button, so there is no need to render another button inside its slot.

fix: remove duplicate button elements in dialog example

---

apps/www/pnpm-lock.yaml
packages/cli/pnpm-lock.yaml
pnpm-lock.yaml

Closes #122 
pnpm implemented a breaking change to their lockfiles in `pnpm@8.6.0`. The change has since been reverted for `pnpm@8.6.2` and onwards.
Here's the related comment and solution: https://github.com/pnpm/pnpm/issues/6648#issuecomment-1588863457.

Fixes `pnpm`'s lockfile version for backwards compatibility 

---

apps/www/src/content/components-json.md

Updated the docs to replace `shadcn-ui@latest` with `shadcn-svelte@latest`.

Update docs to point to shadcn-svelte

---

apps/www/src/content/components/menubar.md

It's a super tiny fix, but I noticed the usage example doesn't work out of the box when copied from the docs to my project.

Fix the shortcut in the menubar example

---

apps/www/mdsvex.config.js

Change the imports on the preview code snippets from `@/components` to `$lib/components` to align with standard Svelte practices.

make preview code imports more sveltish

---

apps/www/src/content/components/select.md

The docs contain an example of a Select component. This example uses a non-existent className prop, which is changed to the class prop in this pull request.

Docs: change className to class prop

---

apps/www/package.json
apps/www/pnpm-lock.yaml
apps/www/src/content/installation.md
apps/www/src/lib/components/docs/theme-customizer/customizer.svelte
apps/www/tailwind.config.js

tailwindcss-animate isn't used no more and should be removed from docs and app
- cleans up the docs and the dependencies / config from tailwindcss-animate

chore: removes config to tailwindcss-animate in docs

---

.changeset/shaggy-eagles-impress.md
packages/cli/src/commands/init.ts
packages/cli/src/utils/templates.ts

tailwindcss-animate isn't used no more and should be removed from init
- cleans up the templates resulting tailwind.config.ts
- removes the dependency to tailwindcss-animate in init

chore: removes config to tailwindcss-animate inside the templates

---

apps/www/src/content/components/data-table.md

Fixed the data-table link so it does not target a 404 page anymore

fix: data table source link

---

apps/www/src/content/installation.md

I've found the 2nd version to be superfluous and all Shadcn components work without it. This is an opportunity to simplify for new users.
(Actually, the entire step could be removed because SvelteKit's default `$lib` alias without any changes to `alias: {}`, but I imagine specifying it gives explicit guidance to devs in case they overrode SvelteKit's default, so I didn't PR that.)

Remove unneeded SvelteKit alias

---

apps/www/src/content/installation.md

During project installation process I have noticed `tailwindcssAnimate` was not found, so I have installed it. But later I have found this pull request #236 that removes `tailwindcssAnimate` from project so I believe this inaccuracy should be removed from `installation.md` as well

chore: remove tailwindcssAnimate from docs

---

apps/www/src/lib/components/docs/site-header.svelte

`supports-backdrop-blur:bg-background/60` does nothing
`supports-[backdrop-filter]:bg-background/60` does something!
see: https://github.com/shadcn-ui/ui/pull/1628

Fix backdrop blur support rule

---

apps/www/src/lib/components/docs/site-footer.svelte

just that (and a `px-8` on medium, to align with the current footer on shadcn/ui)

Footer no longer has a border

---

apps/www/src/content/installation.md
apps/www/src/content/theming.md
apps/www/tailwind.config.js
packages/cli/src/utils/templates.ts

Fixes #333 
Per the TailwindCSS docs [here](https://tailwindcss.com/docs/customizing-colors#using-css-variables), when defining your colors in your configuration file, you need to be sure to include the color space you’re using, and the special `<alpha-value>` placeholder that Tailwind will use to inject the alpha value when using an opacity modifier.
This is useful when controlling the opacity of colours using the colour opacity modifier.
e.g. `bg-indigo-500/50`

fx: add the special `<alpha-value>` placeholder

---

.changeset/long-dingos-work.md
apps/www/src/content/components/card.md

For context, see: #392
- I removed the example with `p` as it is semantically false.
- I changed the examples `tag="h2"` and `tag="h5"` to `tag="h1"` and `tag="h6"` as they are the upper and lower limit of heading.
- Added `...` to show that the property `tag` accept all value in-between the first and the second example.

Fix: <Card.Title> example with `tag="p"`

---

apps/www/src/routes/examples/tasks/(components)/data-table.svelte

I noticed that i missed 2 console logs in task example. This pull request removes them.

Fix: Remove unused consolelog

---

apps/www/src/lib/registry/default/ui/form/form-native-select.svelte
apps/www/src/lib/registry/new-york/ui/form/form-native-select.svelte
apps/www/src/routes/examples/forms/appearance/appearance-form.svelte

Wrapped Select and Chevron in a div for NativeSelect component

---

apps/www/src/content/components/combobox.md

Removed `source` property from Combobox markdown file

---

apps/www/src/routes/examples/tasks/(components)/data-table-column-header.svelte
apps/www/src/routes/examples/tasks/(components)/data-table.svelte

Tasks example renders column id in the column header, the header is a single word in the example, so the example doesn't show the error, but it doesn't render the actual column header. A header set to string 'Hello world' and an id set to 'helloWorld' would render as 'HelloWorld' without this change. This pull request fixes that.

Fix: Tasks example: render column header instead of id

---

apps/www/src/lib/registry/default/ui/table/table-cell.svelte
apps/www/src/lib/registry/default/ui/table/table-header.svelte
apps/www/src/lib/registry/default/ui/table/table-row.svelte
apps/www/src/lib/registry/new-york/ui/table/table-cell.svelte
apps/www/src/lib/registry/new-york/ui/table/table-header.svelte
apps/www/src/lib/registry/new-york/ui/table/table-row.svelte

Addresses issue https://github.com/huntabyte/shadcn-svelte/issues/464. This adds `on:click` and `on:keydown` to the following table components to make them clickable. The `on:keydown` is added for accessibility.
- table-cell.svelte
- table-header.svelte
- table-row.svelte

Make table components clickable

---

apps/www/package.json
apps/www/pnpm-lock.yaml
apps/www/src/lib/components/docs/theme-customizer/customizer.svelte
apps/www/src/lib/components/docs/theme-customizer/theme-customizer.svelte

just wanted to update `mode-watcher`.
now with `mode-watcher` > `0.1.0`, `$mode` is (more accurately) `undefined` until the stores have loaded correctly.
this is usually not a problem for FOUC sensitive applications since those should rely on the presence of the `dark` class in the `html` element and use the `dark:` tailwind variant.
for less FOUC sensitive applications like the styling of these buttons, it should be perfectly fine to fallback to a certain theme (`"dark"` in this case). the fallback is not really needed but it's there so that `pnpm check` is happy

chore: update mode-watcher & add fallback mode before stores load

---

apps/www/src/content/installation.md

with this commit, a `.eslintrc` file _should_ be added to the `.../components/ui` folder when initialising a new project with `npx shadcn-svelte@latest init`.
I write _should_ because I do not know how to test this 😅 so I have coded it "blind"
I added this because it's a common problem that people run into, this solution works without modifying existing project wide `.eslintrc.cjs` files.
a downside is that this is added without checking if the project uses `eslint` to begin with. a check for that could be added I guess!
feel free to close if you dislike this idea - no problem

docs: add ESLint configuration section to installation docs

---

apps/www/src/lib/registry/new-york/example/dialog-demo.svelte

Fix browser warning in demo code regarding unassociated <input> in <label>

docs: associate label with input in example

---

.changeset/young-toys-doubt.md
packages/cli/src/commands/init.ts

fix: Only delete the tailwind config if it's a `.cjs` file

---

apps/www/src/routes/examples/authentication/(components)/user-auth-form.svelte

Just fix brand name typo from Github to GitHub

fix: typo brand Github to GitHub

---

apps/www/src/content/components/date-picker.md

Fix for #593.
The component source link for date picker gave 404.
Because the date picker component is a composition of multiple componenets. I changed the link to the demo code instead.

docs: update source link for date-picker

---

apps/www/src/content/components/drawer.md

removed an unnecessary closing Button tag in the Drawer component, which caused a mismatched tag error.

docs: Removed an un unnecessary closing Button tag

---

.changeset/new-lizards-marry.md
apps/www/scripts/registry.ts
apps/www/src/content/components/sonner.md
apps/www/static/registry/index.json
apps/www/static/registry/styles/default/sonner.json
apps/www/static/registry/styles/new-york/sonner.json

The Sonner component needs us to specify a theme, otherwise it will default to the system preference. If the `<ModeWatcher />` component is not being used, it will also default to `"system"`. If you decide you do not want to use `mode-watcher`, you can simply remove it from your component and replace it with whatever you'd like.
This is aligned with how the original shadcn/ui's installation works, where `next-themes` is installed to keep the toast theme in sync with your app's theme.
Fixes: #595

fix: add mode-watcher to Sonner registry deps

---

apps/www/package.json
apps/www/pnpm-lock.yaml

Update `vaul-svelte` and `bits-ui` to `@latest` for bug fixes, more specifically related to drawer closing behavior.

update vaul svelte & bits

---

apps/www/src/lib/registry/default/ui/input/index.ts
apps/www/src/lib/registry/default/ui/input/input.svelte
apps/www/src/lib/registry/new-york/ui/input/index.ts
apps/www/src/lib/registry/new-york/ui/input/input.svelte

I've recently found immense value in using the `focusout` and `focusin` events on input elements locally and realised this functionality is absent in the shadcn-svelte's Input component. Recognising the potential benefits to others, I've decided to contribute by integrating this feature into the library.
This enhancement allows for more dynamic and responsive user interactions. For instance, consider a scenario where you need to display a key securely that can toggle its visibility. Upon focusing out of the Input component, the key gets concealed again. Here's how you can utilise this feature:
```svelte
<div class="relative flex flex-row items-center text-muted-foreground">
<Input
type="password"
class="my-2 pr-[54px]"
value={key}
readonly
disabled
bind:this={key_element} …
```

feat: forward  `focusin` and `focusout` for `Input` components 

---

apps/www/src/lib/components/docs/table-of-contents.svelte

Closes: #433 
We're now ensuring that each heading `id` is unique when generating the table of contents.

fix: duplicating ToC ids

---

apps/www/src/content/installation.md

The installation instruction for plain svelte + vite (i.e. _not_ sveltekit) is missing step to also edit the `resolve` config in `vite.config.js`, so that vite can understand the `$lib` alias.
I've read the contributing guide, and I think I don't need to open an issue because this PR is trivial enough.

fix(docs): installation instruction for plain svelte vite

---

apps/www/src/routes/+layout.svelte

First-time contributor, feel free to shout at me 😆 
I treated this as a small fix which is why I didn't file an issue.
This PR adds "data-vaul-drawer-wrapper" to the root docs "layout.svelte" which allows the vaul-svelte drawer to properly scale the background.
https://github.com/huntabyte/shadcn-svelte/assets/102172929/a52482e0-c971-4745-96b4-f1cedc1a3baa
https://github.com/huntabyte/shadcn-svelte/assets/102172929/ff8eaf6a-a18f-45d6-ad6f-440e3d571e59
https://github.com/huntabyte/shadcn-svelte/assets/102172929/853c70e0-97b6-4fa5-b1be-4066b65ae7a8
As I said, first-time contributor so sorry if I did anything wrong, I'm here to learn 😄

docs: Add "data-vaul-drawer-wrapper" data attribute to the root layout

---

apps/www/src/lib/components/docs/examples-nav/examples-nav.svelte
apps/www/src/routes/examples/forms/(components)/sidebar-nav.svelte

https://github.com/huntabyte/shadcn-svelte/assets/53095479/2c90f268-7540-4d62-b7ad-f99dffea7d7f
https://github.com/huntabyte/shadcn-svelte/assets/53095479/0cf4e622-2786-484b-afc0-e5dc9dac4097
https://github.com/huntabyte/shadcn-svelte/assets/53095479/e4833559-90d9-47dd-95cf-ecf4da91d13a
https://github.com/huntabyte/shadcn-svelte/assets/53095479/6062736b-61a8-48cf-9b06-b1a1d787aa66

docs: add active tab crossfade transition to examples

---

apps/www/src/content/components/form.md
apps/www/src/lib/registry/default/example/form-demo.svelte
apps/www/src/lib/registry/new-york/example/form-demo.svelte
apps/www/src/routes/docs/[...slug]/+page.server.ts
apps/www/src/routes/examples/forms/+page.server.ts
apps/www/src/routes/examples/forms/account/+page.server.ts
apps/www/src/routes/examples/forms/appearance/+page.server.ts
apps/www/src/routes/examples/forms/notifications/+page.server.ts

This is a small PR for updating the forms documentation. It also fixes the form's data loading by awaiting all `superValidate` functions in `+page.server.ts` files.
Finally, the examples' forms now display sonner's toasts to show how to handle the form's results in the UI.
It will render different toasts depending on the form's result.
Enjoy ! 🎉

docs(forms): :memo: add options to forms

---

apps/www/src/lib/registry/default/example/cards/calendar.svelte
apps/www/src/lib/registry/new-york/example/cards/calendar.svelte

Closes: #660
The card with the Calendar (with ``max-w-[260px]``) caused the buttons inside the component to overflow (more noticeable with the Default theme). Changing to ``max-w-[280px]`` fixes it (and syncs with the original shadcn/ui)

fix: calendar max-width on Themes

---

apps/www/mdsvex.config.js
apps/www/src/lib/components/docs/copy-button.svelte

Fixes #642.
I finally got time to lean into this feature. What took time was getting more familiar with mdsvex and rehype/remark plugins, which I never really did before (only using `md`➜`html`, never contributed to them, or even wondered how they were working).
At the end of the day, instead of blindly copying what shadcn did [for the original website](https://github.com/shadcn-ui/ui/blob/main/apps/www/lib/rehype-npm-command.ts), I preferred a Sveltier approach: simpler, type-safe and shorter.
Hope you like it!
> I also added some comments in the mdsvex config file as I was messing around, I can totally remove that if you think it's unnecessary/not the point of the PR

docs: Add package manager dropdown on copy button

---

apps/www/src/lib/registry/default/ui/select/select-trigger.svelte
apps/www/src/lib/registry/new-york/ui/select/select-trigger.svelte

Closes #689 
Makes Select components more consistent with the original ShadCn repo, by disabling line wrapping in select trigger.
Before:
After:
Compare https://www.shadcn-svelte.com/themes (width set to 1280px)

fix: line wrapping in Select component

---

apps/www/src/lib/registry/default/ui/menubar/menubar-sub-content.svelte
apps/www/src/lib/registry/new-york/ui/menubar/menubar-sub-content.svelte

This should fix #700. When I was looking at [shadcn-ui](https://ui.shadcn.com/docs/components/menubar) I noticed that they are wrapping the subcontent with 2 divs instead of one as we do here. But I do not see why it's necessary. 
This pr fixes the issue without making any bigger adjustments. Let me know if you disagree @huntabyte

fix: menu `SubContent` with min width

---

apps/www/src/lib/registry/default/example/cards/report-issue.svelte
apps/www/src/lib/registry/default/ui/input/input.svelte
apps/www/src/lib/registry/default/ui/select/select-trigger.svelte
apps/www/src/lib/registry/default/ui/textarea/textarea.svelte
apps/www/src/lib/registry/new-york/example/cards/report-issue.svelte
apps/www/src/lib/registry/new-york/example/cards/share.svelte
apps/www/src/lib/registry/new-york/ui/button/index.ts
apps/www/src/lib/registry/new-york/ui/input/input.svelte
apps/www/src/lib/registry/new-york/ui/select/select-trigger.svelte

#691 Introduced some new issues (I was not able to repro, but found an issue in the css) encountered by @phenomen [here](https://github.com/huntabyte/shadcn-svelte/commit/811a06222bffcdd1c9cae8c211cfcf44f7589a48#commitcomment-137885500)
As I was the culprit here, I'm fixing this ASAP. This PR addresses those issues.
I now completely updated the select-trigger styling to match that of shadcn-react.
@huntabyte please note the bg-transparent -> bg-background and the whitespace-nowrap. These are in the react-version but were not in shadcn-svelte yet. If you look at shadcn-svelte and shadcn's themes page, the background colors of inputs/selects/comboboxes etc are not 1:1.

docs: fix select styles

---

apps/www/src/lib/registry/default/ui/calendar/calendar-cell.svelte
apps/www/src/lib/registry/new-york/ui/calendar/calendar-cell.svelte

fixed the border radius of the selected day in the calendar component

fix: calendar selected day border radius

---

apps/www/src/lib/components/docs/copy-button.svelte

Because pnpx is [deprecated](https://github.com/pnpm/pnpm/pull/3652) and doesn't work in v7+ versions on pnpm.

fix: pnpx -> pnpm dlx in copy button

---

apps/www/src/lib/registry/default/ui/menubar/menubar-sub-trigger.svelte
apps/www/src/lib/registry/new-york/ui/menubar/menubar-sub-trigger.svelte

Small PR that fixes the Menubar.Sub style when it's disabled.
Here's how it looks like now:

fix: grey out Menubar.Sub when disabled

---

apps/www/src/lib/components/docs/theme-customizer/customizer.svelte

Fix the color circles in /themes within the Customize button popover (sometimes) not displaying.
> [!NOTE]
> On prod, the color is sometimes resolved as `undefined` (the missing `)` is not the single issue), but for some reason I _cannot_ reproduce it in dev.  
> So I'm not sure the issue is 100% fixed but it seems to be working in the Vercel Preview

fix(www): Fix color circles not rendering in /themes

---

apps/www/src/lib/registry/default/example/button-icon.svelte
apps/www/src/lib/registry/new-york/example/button-icon.svelte

Should be `class` instead of `className`.
I spent too long trying to figure out why the styles weren't applying 😅

docs: button icon example typo

---

apps/www/src/content/components/data-table.md

I noticed just two small "issues" when reading through the docs of data table, nothing fancy.
1. Added a line highlight to one change that was missing.
**Before**
**After**
2. Updated a space-x-2 to space-x-4 since it was changed between the first and the next code block that Pagination appears.

docs: update two small mistakes on data-table walkthrough

---

apps/www/src/lib/registry/default/ui/switch/switch.svelte

PR #220 added these events to `new-york/ui/switch.svelte`, but not into the `default` version of this component. This small change closes that gap, and also adds `type $$Events` for further parity with the New York component.

chore: add event forwarding & types for default/ui/switch

---

apps/www/src/lib/components/docs/charts/helpers.ts
apps/www/src/lib/components/docs/charts/metric.pcss
apps/www/src/lib/components/docs/charts/metric.svelte
apps/www/src/lib/components/docs/charts/revenue.svelte

Fixes: #789 
There is currently a warning/log.
```
[vite-plugin-svelte] /src/lib/components/docs/charts/metric.svelte:42:1 No scopable elements found in template. If you're using global styles in the style tag, you should move it into an external stylesheet file and import it in JS. See https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#where-should-i-put-my-global-styles.
```
This is on me. Because of an issue from Unovis,(the `style` prop issue), there is currently no way of overriding some styles, so what came to me right away was just using the `style` tags, and thus the warning. In the past, I just put said styles in a separate file as recommended by the warning, but I wanted to hear from you about an ideal approach/resolution.
P.S. If there is anything to …

docs: improve metric cards

---

apps/www/src/lib/config/docs.ts

the github url for the mail example in the docs leads to a 404

fix(docs): mail example github code url

---

apps/www/src/routes/examples/mail/(components)/mail-display.svelte
apps/www/static/registry/index.json
apps/www/static/registry/styles/default-js/drawer.json
apps/www/static/registry/styles/default/drawer.json
apps/www/static/registry/styles/new-york-js/drawer.json
apps/www/static/registry/styles/new-york/drawer.json

Minor styling issue; previously set the padding on the Calendar itself - terrible idea.
---
P.S. I don't know why the registry files are being affected - just did `pnpm dev` and they "built". 🤷‍♂️

docs: improve Calendar styling on Mail example

---

apps/www/src/lib/registry/default/example/dialog-demo.svelte

Added the html `for` attribute in labels for best practice. For some reason, this was featured in [New York](https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/registry/new-york/example/dialog-demo.svelte) style but not default.

fix: add `for` to labels in default/example/dialog-demo.svelte

---

apps/www/src/lib/registry/default/ui/input/index.ts
apps/www/src/lib/registry/default/ui/popover/index.ts
apps/www/src/lib/registry/new-york/ui/input/index.ts
apps/www/src/lib/registry/new-york/ui/popover/index.ts

I needed to close the popover after the user clicks a button in the popover content.  That button would fire an event and does something.  However it would not close the popover.  By adding the existing popover close as a child its now possible to do this.
```
<Popover.Root let:ids> 
<Popover.Trigger asChild let:builder>
<Button builders={[builder]} variant="outline">
<Upload/>
Upload PDF
</Button>
</Popover.Trigger>
<Popover.Content> 
<Popover.Close asChild let:builder>
<FileSelect builder={builder}/>
</Popover.Close>
</Popover.Content>
</Popover.Root>
```
The inside my FileSelect component I can just use a button that does the file upload and it would close the popover.
```
<Input type="file" on:change={handleFileChange} />
<Button class="" on:click={handleFileUpload} …
```

feat: Add Popover Close and minor type improvment

---

apps/www/src/lib/registry/default/example/scroll-area-both.svelte

Add width to the container of the `default` scroll area demo showcasing both horizontal and vertical scrollbars.

fix: scroll area demo

---

.changeset/famous-suns-compete.md
packages/cli/.prettierrc
packages/cli/src/astravel/attachComments.js
packages/cli/src/commands/add.ts
packages/cli/src/commands/init.ts
packages/cli/src/commands/update.ts
packages/cli/src/index.ts
packages/cli/src/utils/find-tsconfig.ts
packages/cli/src/utils/get-config.ts
packages/cli/src/utils/logger.ts
packages/cli/src/utils/registry/index.ts
packages/cli/src/utils/set-config.ts
packages/cli/test/commands/init.spec.ts
packages/cli/test/utils/get-config.spec.ts

Fixes #827.
As per our discussion, warns the user at the end of the update process whenever a processed component no longer uses some files present in its directory.
Additionally, sort the components processed by name, and display the progress through an `index + 1/total` counter.
Demo:
https://github.com/huntabyte/shadcn-svelte/assets/43064022/2a5ef818-3adb-4ba4-b57a-b475bbe0a1ea

feat(cli): Warn about deleted components, order and progress

---

apps/www/package.json
apps/www/src/content/components/data-table.md
apps/www/src/content/index.md
apps/www/src/lib/components/docs/icons/index.ts
apps/www/src/lib/registry/default/example/alert-destructive.svelte
apps/www/src/lib/registry/default/example/button-loading.svelte
apps/www/src/lib/registry/default/example/combobox-dropdown-menu.svelte
apps/www/src/lib/registry/default/example/combobox-popover.svelte
apps/www/src/lib/registry/default/example/data-table/data-table-actions.svelte
apps/www/src/lib/registry/default/example/dropdown-menu-demo.svelte
apps/www/src/lib/registry/default/ui/breadcrumb/breadcrumb-ellipsis.svelte
apps/www/src/lib/registry/default/ui/pagination/pagination-ellipsis.svelte
apps/www/src/routes/examples/mail/(components)/mail-display.svelte
apps/www/src/routes/examples/mail/config.ts
apps/www/src/routes/examples/mail/icons.ts
pnpm-lock.yaml

Closes: #897 
- Updates the icon package (lucide-svelte) and renames the icons to the new names.
- I didn't build the registry because you mentioned some time back that the registry is built regardless on each app build/deployment, right? @huntabyte 
- Forgive the auto imports sorting/organization. I forgot to disable this rule in my IDE. Hope you don't mind.
```json
// Auto sort/move imports on save
"editor.codeActionsOnSave": {
"source.organizeImports": "always"
}
```

chore: update `lucide-svelte` & icon names

---

apps/www/src/content/components/form.md

In step 5 of the [form example](https://www.shadcn-svelte.com/docs/components/form), the highlighting of what lines need to be added is off. 
The last semicolon isn't highlighted, which could cause syntax errors for anyone following along with the example.
Shifting the highlighting by 1 line fixes this.

docs: fix wrong line highlighting in form example

---

.gitignore
apps/www/package.json
apps/www/src/__registry__/index.js
apps/www/src/lib/components/docs/dashboard/dashboard-page.svelte
apps/www/src/routes/+page.svelte
apps/www/src/routes/examples/authentication/+page.svelte
apps/www/src/routes/examples/cards/+page.svelte
apps/www/src/routes/examples/forms/+layout.svelte
apps/www/src/routes/examples/mail/(components)/mail.svelte
apps/www/src/routes/examples/music/+page.svelte
apps/www/src/routes/examples/playground/+page.svelte
apps/www/src/routes/examples/tasks/+page.svelte
apps/www/static/registry/styles/default-js/breadcrumb.json
apps/www/static/registry/styles/default-js/pagination.json
apps/www/static/registry/styles/default/breadcrumb.json
apps/www/static/registry/styles/default/pagination.json
apps/www/vite.config.ts
pnpm-lock.yaml

While `@sveltejs/enhanced-img` is a great plugin for optimizing images for SK, it unfortunately slows down our build pipeline by a significant amount. Previously, it would take a little under 2 minutes to complete a fresh build, whereas now it takes about 8 minutes. 
Currently, there's no available plugin/config option to cache the generated images, meaning that all images need to be processed (twice!) on _every_ build. Our little GH runner just can't keep up. 
We'll reevaluate once the ability to cache is implemented.

chore: Remove `@sveltejs/enhanced-img`

---

.changeset/twenty-apes-rescue.md
packages/cli/src/commands/update.ts
packages/cli/src/utils/get-config.ts

Fixes #914, which fixes #844.
Fix incorrect falsy value when checking if there are components to remove at the end of the update process.
Also, fix the init script, which incorrectly creates a `utils.js.ts` file. The file extension is already added upon creation, so we don't need this. We might however need the file extension within the config file or a better alias resolution mechanism, so maybe I should move that out of this PR? Or maybe it's a good first fix for the file creation?

fix(cli): Fix update script end log incorrectly displaying, fix init script utils file creation

---

apps/www/src/routes/examples/tasks/(components)/data-table-column-header.svelte
apps/www/src/routes/examples/tasks/(components)/data-table-pagination.svelte
apps/www/src/routes/examples/tasks/(components)/data-table-view-options.svelte
apps/www/src/routes/examples/tasks/(components)/data-table.svelte

docs: Update tasks example to be 1:1 with original

---

.changeset/fifty-falcons-dream.md
packages/cli/package.json
packages/cli/src/index.ts
packages/cli/src/utils/get-package-manager.ts
packages/cli/src/utils/prompts.ts
packages/cli/src/utils/registry/index.ts
packages/cli/src/utils/resolve-imports.ts
packages/cli/tsconfig.json
pnpm-lock.yaml

`tsconfig-paths` is a bit of a chonky dependency. I've replaced it for a custom path alias resolver that's much simpler for our needs.

chore: More CLI optimizations

---

apps/www/src/lib/components/docs/copy-button.svelte
apps/www/src/lib/components/docs/hex-to-channels.svelte

Copy buttons for HSL and RGB inputs was using the same color as background, making them invisible on https://www.shadcn-svelte.com/docs/theming.  
- updated `CopyButton` color and hover color for these instances
- fix position of the CopyButtons
- moved `CopyButton` below input to focus on input before focus on copy buttons when navigating using keyboard
- remove tabindex from SVGs, which was causing double focus, both for button and SVGs when using navigating using keyboard.

fix: make copy Button` visible in hex to channel inputs

---

apps/www/src/lib/registry/default/block/dashboard-03.svelte
apps/www/src/lib/registry/new-york/block/dashboard-03.svelte

Fixes #961 by increasing header height to 57px, aligned to height in equivalent shadcn/ui block.

fix: header height in `dashboard-03`

---

apps/www/src/lib/config/docs.ts

Appended (app) route group to source code links.
e.g
from
`-code: "https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/routes/examples/mail",`
to
`code: "https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/routes/(app)/examples/mail",`

fix: Links to view source code in /examples

---

apps/www/src/routes/(app)/examples/forms/account/account-form.svelte

fixes #884 by hardcoding the timezone to UTC when the user selects a date of birth

fix: use UTC timezone for DOB field in account form example

---

apps/www/src/content/installation/index.md

Currently, if you head over to https://www.shadcn-svelte.com/docs/installation#eslint-configuration, you'll notice that the ignore pattern displayed is
```
"varsIgnorePattern": "^\$\$(Props|Events|Slots|Generic)$"
```
This is wrong, since pasting that in your IDE yields:
```
Unnecessary escape character: \$.eslint[no-useless-escape](https://eslint.org/docs/latest/rules/no-useless-escape)
Unnecessary escape character: \$.eslint[no-useless-escape](https://eslint.org/docs/latest/rules/no-useless-escape)
```
The strange thing is, in the content docs, the correct config is written down, but for some reason some backslashes are "escaped."
I don't know if my fix is ideal, but I added extra backslashes to account for this, such that the correct var pattern is rendered in the UI.
i.e.
``` …
```

docs: fix varsIgnorePattern in .eslintrc

---

apps/www/src/lib/registry/default/ui/table/table.svelte
apps/www/src/lib/registry/new-york/ui/table/table.svelte
apps/www/src/routes/(app)/examples/tasks/(components)/data-table-faceted-filter.svelte
apps/www/src/routes/(app)/examples/tasks/(components)/data-table-row-actions.svelte
apps/www/src/routes/(app)/examples/tasks/(components)/data-table-toolbar.svelte
apps/www/src/routes/(app)/examples/tasks/(components)/data-table.svelte
apps/www/static/registry/styles/default-js/table.json
apps/www/static/registry/styles/default/table.json
apps/www/static/registry/styles/new-york-js/table.json
apps/www/static/registry/styles/new-york/table.json

Faced this issue in my own project, and remembered I copied it from this example.
~The original shadcn does not need this workaround.. can't figure out why...~
Before:
- Shrink the page horizontally so that the table starts overflow-scrolling by a big chunk (>100px), the sr-only text in the triple dots menu will start overflowing the page too.
https://github.com/huntabyte/shadcn-svelte/assets/11229056/802bb127-2e83-499f-9230-9d5ba0c06415
After:
~- By wrapping the sr-only text in a relative span, as explained by a _maintainer_ of tailwindcss [here](https://github.com/tailwindlabs/tailwindcss/discussions/12429), we can prevent the page from overflowing... nice!~
The original shadcn fixes this using relative on the table component, instead of per sr-only span.
Last commit fixes this. …

fix: tasks example causing overflow on the page

---

.changeset/fluffy-cobras-decide.md
packages/cli/src/index.ts
packages/cli/src/utils/auto-detect.ts
packages/cli/src/utils/prompt-helpers.ts

Bun's compatibility module for Node's `fs` module is [incomplete](https://bun.sh/docs/runtime/nodejs-apis#node-fs). This resulted in an error when trying to access the `path` prop of a Dirent, which didn't exist (see: https://github.com/oven-sh/bun/issues/7358). 
In this particular case, the fix was trivial. However, future incompatibility issues isn't guaranteed to be as easy. Additionally, their compatibility promise for Node is incomplete. As such, Bun will stay unsupported.
I've also changed the "unsupported runtime error" message into a warning so it's no longer a hard block.
Closes #1003
Closes #1009 
- If your PR isn't addressing a small fix (like a typo), it references an issue where it is discussed ahead of time and assigned to you. In many cases, features are absent for a …

chore: Change unsupported runtime error

---

apps/www/src/content/cli.md

I have added the option to skip the confirmation prompt to the `update` command to the cli docs. The option to the command is already present in the cli.
I have also written two description texts of options of the `add` command in lower case and thus aligned them with the other description texts. I hope it's okay that I have added this in this PR.

docs: add docs to skip confirmation prompt to `update` command

---

apps/www/src/lib/registry/default/example/cards/report-issue.svelte
apps/www/src/lib/registry/new-york/example/cards/report-issue.svelte

Fix an issue in "/themes" page - report issue component:
"line-clamp-1" is setting the display to "-webkit-box" which overwrite the "flex" class therefore I have remove "line-clamp-1" from the classes and add "overflow-hidden" instead.
Closes: #1020

fix: styles for `Select.Trigger`

---

apps/www/src/lib/registry/default/block/dashboard-06.svelte

On the dashboard block, dashboard-06, some of the columns have the class table.-cell. I have went in and replaced them with table-cell.
Without this fix, the columns with table.-cell will not show at any screen width.

fix: block - default dashboard-06 table columns

---

apps/www/src/lib/components/docs/block-preview.svelte
apps/www/src/lib/registry/default/ui/drawer/drawer-content.svelte
apps/www/src/lib/registry/default/ui/progress/progress.svelte
apps/www/src/lib/registry/default/ui/skeleton/skeleton.svelte
apps/www/src/lib/registry/default/ui/textarea/textarea.svelte
apps/www/src/lib/registry/new-york/ui/drawer/drawer-content.svelte
apps/www/src/lib/registry/new-york/ui/progress/progress.svelte
apps/www/src/lib/registry/new-york/ui/skeleton/skeleton.svelte
apps/www/src/lib/registry/new-york/ui/textarea/textarea.svelte
package.json
pnpm-lock.yaml

Fixes the issue raised by Rich Harris here: https://github.com/sveltejs/svelte/issues/11052, wherein it is pointed out how self closing tags in HTML are a lie, and `<div />` is equivalent to an unclosed `<div>`.
I simply ran the self closing tags migration provided by `svelte-migrate` on the project.

fix: Self closing tags issue

---

apps/www/src/lib/components/docs/block-copy-code-button.svelte

Just an example, the data-x-block attributes are a bit annoying when copying the code.
Added function that uses regex to remove the data-x-block-name and description attributes and leaves a clean element.
```
<Card.Root data......" class="abc"> becomes <Card.Root class="abc">
<Card.Root data......"> becomes <Card.Root>
```
No leftover whitespace AFAIK.

feat: data-attribute-remover

---

apps/www/src/lib/registry/default/ui/dialog/index.ts
apps/www/src/lib/registry/new-york/ui/dialog/index.ts

This PR exposes the DialogPrimitive.Close as DialogClose to give the ability to use a button to close a dialog.
Code according to the solution discussed in this discussion #1030 
Solution to issue #1029

feat: Ability to add a button to close a dialog

---

apps/www/src/lib/registry/default/block/dashboard-01.svelte

Fixes a minor issue where the dropdown wasn't showing on click (reproducible from https://www.shadcn-svelte.com/blocks#dashboard-01)
Repro: Click the user icon in the top-right of the page.
Expected result: Dropdown shows up
Actual result: Nothing happens
P.S. Let me know if this should be edited elsewhere, I was just playing around with the code locally.

fix: dashboard-01 dropdown not showing

---

apps/www/src/lib/registry/default/ui/carousel/carousel.svelte
apps/www/src/lib/registry/default/ui/carousel/context.ts
apps/www/src/lib/registry/new-york/ui/carousel/carousel.svelte
apps/www/src/lib/registry/new-york/ui/carousel/context.ts

> Had briefly touched on this is in the server, bringing it here for your consideration;
This P.R lays the groundwork necessary to create a dots-scroll-to feature like in the video. From now on, one need only reach into the context and grab these stores+function and style however they wish.
```ts
const { scrollTo, scrollSnaps, selectedIndex } = getEmblaContext('<Carousel.Dots/>');
```
It's pretty easy to set up yourself, but having it come with the `carousel` component saves some time. 🙂 
(And I don't think this introduction violates/deviates from the original, wouldn't you agree? - at least components-wise)
---
https://github.com/huntabyte/shadcn-svelte/assets/87414827/bc054fdc-503d-4e57-9801-0628366cdbc0
- If your PR isn't addressing a small fix (like a typo), it references an issue …

feat: expose `scrollSnaps` `selectedIndex` `scrollTo`

---

.changeset/moody-seas-compete.md
packages/cli/src/commands/add.ts
packages/cli/src/utils/registry/index.ts

closes #1056
If a component that uses a registry dependency (e.g. `carousel` depends on `button`) is selected, and the user already has that dependency installed (in this case, `button`), the user will be prompted to see if they'd like to overwrite it.

fix: Allow a registry dependency to be optionally overwritten

---

apps/www/src/lib/registry/default/ui/carousel/carousel.svelte
apps/www/src/lib/registry/new-york/ui/carousel/carousel.svelte

Follow-up for #1052 
I'm really sorry for forgetting this; glad I was reminded of it when doing some Embal-related research here: https://github.com/davidjerleke/embla-carousel/discussions/847#discussioncomment-9260698
Speaking of, wanted to send a P.R for initializing the view slides as well, but that sounds too specific (like my use case), thus forewent that.
Thanks.

feat: initialize `scrollSnapsStore` on init

---

apps/www/src/lib/registry/default/ui/input/input.svelte
apps/www/src/lib/registry/new-york/ui/input/input.svelte

> [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
https://chromestatus.com/feature/5745543795965952
repro:
https://stackblitz.com/edit/github-ufxfb8?file=src%2Flib%2Fcomponents%2Fui%2Finput%2Finput.svelte
See the logs in the browser

fix: input wheel event violation

---

apps/www/src/content/components/data-table.md
apps/www/src/lib/registry/default/example/cards/data-table.svelte
apps/www/src/lib/registry/default/example/data-table-demo.svelte
apps/www/src/lib/registry/new-york/example/cards/data-table.svelte
apps/www/src/lib/registry/new-york/example/data-table-demo.svelte
apps/www/src/routes/(app)/examples/data-table/data-table.svelte
apps/www/src/routes/(app)/examples/tasks/(components)/data-table-pagination.svelte

Reverts huntabyte/shadcn-svelte#1075
This shouldn't have been changed given that we're following `svelte-headless-table`'s convention of naming it `page`. It also caused parts of our docs to be inconsistent now too, where `page` was being defined and `.pagination` was being used.
closes #1079

Revert "docs: pluginState.page is now pluginState.pagination"

---

apps/www/src/lib/registry/default/ui/textarea/textarea.svelte

The default textarea component was missing the custom event types. This fix makes the components' event typing work the same way as other components do.
The new york variant is already typed correctly so only the default needs to be changed.

fix: default textarea event types

---

apps/www/src/routes/(app)/examples/cards/(components)/report-issue.svelte

This pull request addressed #1121 
Fix UI bug for examples/card for one of the select fields by adding a flex. 
Look for the bottom right corner
Before: 
After:

docs: Fix overflow issue with select in the card example

---

apps/www/src/routes/(app)/examples/mail/(components)/mail.svelte

The landing/examples page's mail example has a searchbox that contains a search icon.
The icon wasn't centered. Quick fix.
Before:
Now:
Have a nice day, hope I could help.
Cheers!

fix: search icon position

---

apps/www/src/content/components/data-table.md

As per #1126, this is to fix an issue in the guide code (in the Data Table section), whereby, when I hide the email column then all the rows are removed, and the row selection checkbox is checked.

docs: fix empty data table when the email column is hidden

---

apps/www/src/routes/(app)/docs/[...slug]/+page.svelte

Fixes #1085 by wrapping “On this Page” table of contents in a ScrollArea.
Also adjusted top alignment (see screenshot).

docs: fix scrollable table of contents #1085

---

apps/www/src/lib/registry/default/ui/select/select-trigger.svelte
apps/www/src/lib/registry/new-york/ui/select/select-trigger.svelte
apps/www/src/styles/globals.css

- Fix placeholder https://github.com/huntabyte/shadcn-svelte/issues/1037
- Fix aria-invalid border
- Fix focus. It shouldn’t have focus on press. It should have focus upon exit/selection, but it seems melt-ui is not triggering it: https://melt-ui.com/docs/builders/select
- Focus color was too dim on dark mode

chore: select component improvements

---

apps/www/src/content/components/carousel.md

This PR fixes a small typo on the Carousel docs, when importing the CarouselAPI the import statement is incorrect for the type. Changes 'CarouselApi' to 'CarouselAPI'.

docs: fix typo on carousel documentation for CarouselAPI import

---

apps/www/package.json
apps/www/src/lib/stores/config.ts
apps/www/src/lib/utils.ts
pnpm-lock.yaml

The PR updates a superseded dependency that doesn't receive updates anymore because it was moved to a new package name.
Ref.: https://www.npmjs.com/package/svelte-local-storage-store
<br>
I'm adding a little justification, since the contribution is missing the first step of the contribution guidelines of opening an issue first:
- Based on the issue templates, I couldn't classify a category that would fit to open an issue prior to the PR. 
- The rationale of the guidelines is to save a contributor's time. The most time-efficient way I could think of for this specific change was to open the PR directly. I'm okay if it's closed and not merged, as this would have saved time for me. Please don't hesitate to close it if the changes are not appropriate.

chore: update superseded package

---

apps/www/src/lib/components/docs/mode-toggle.svelte
apps/www/src/lib/components/docs/site-header.svelte

Current:
|shadcn-svelte|shadcn/ui|
|-|-|
|![Screenshot_20240714_132306](https://github.com/user-attachments/assets/9f5a3cee-f272-40c6-8568-0739197c4290)![Screenshot_20240714_132257](https://github.com/user-attachments/assets/6c8781d8-534e-48bc-b767-f8712aa76345)|![Screenshot_20240714_132333](https://github.com/user-attachments/assets/9eed9c32-77fb-48f3-af29-a87a1039d023)![Screenshot_20240714_132337](https://github.com/user-attachments/assets/16d25978-d67c-45d4-969d-e6e0c508e391)|
The update makes the button sizes uniform and adapts them to the upstream style.
It does so by using the same tailwind classes that shadcn is using (ref. https://github.com/shadcn-ui/ui/blob/f170784f78b553641abbfe17c76a500a9563cf50/apps/www/components/site-header.tsx#L33). Personally, for squares, I would use the …

docs: make button size in site-header uniform

---

.changeset/afraid-melons-remain.md
.changeset/plenty-rockets-hear.md
apps/www/src/content/cli.md
apps/www/src/lib/components/docs/manual-install.svelte
packages/cli/src/commands/add.ts
packages/cli/src/commands/init.ts
packages/cli/src/commands/update.ts
packages/cli/test/commands/init.spec.ts

- fixes #1196
- Updates docs for init command including `Install after --nodeps` instructions
New Init:
```
Usage: shadcn-svelte init [options]
initialize your project and install dependencies
Options:
-c, --cwd <cwd>            the working directory. defaults to the current directory.
--nodeps                   disable adding & installing dependencies (advanced) (default: false)
--style <name>             the style for the components (choices: "default", "new-york")
--base-color <name>        the base color for the components (choices: "slate", "gray", "zinc", "neutral", "stone")
--css <path>               path to the global CSS file
--tailwind-config <path>   path to the tailwind config file
--components-alias <path>  import alias for components
--utils-alias <path>       import alias …
```

feat: Add `--no-deps` flag to `init` command

---

sites/docs/src/lib/registry/default/ui/separator/separator.svelte
sites/docs/src/lib/registry/new-york/ui/separator/separator.svelte

Fixes height of vertical separator when parent container doesn't have a defined height. Closes https://github.com/huntabyte/shadcn-svelte/issues/1149.

fix: Vertical separator height

---

sites/docs/src/content/installation/sveltekit.md
sites/docs/src/content/installation/vite.md

Two small typos on the global CSS file path

docs: fix installation guide typos

---

sites/docs/src/content/components/sonner.md

Just spent more time than I am proud of trying to figure this one out. But I do think its a pretty easy mistake to make if you are trying to use intellisense imports.
This is an obvious mistake but if you aren't paying attention and could be useful to mention in the installation instructions.
```ts
// incorrect
import { Toaster } from "svelte-sonner";
// correct
import { Toaster } from "$lib/components/ui/sonner"; 
```
Obviously when you do this you miss out on the entire reason of adding the sonner component through shadcn as none of the styles are applied.
I think adding a note would help anyone else who makes this mistake.

docs: Add note to Sonner component

---

sites/docs/src/routes/(app)/examples/music/(components)/album-artwork.svelte

docs: make album artwork same size on music example

---

sites/docs/src/lib/components/docs/nav/main-nav.svelte

My previous contribution (tailwind colors page) introduced a new link "colors" to the navbar. This causes the search bar to cover nav links on md-lg viewport widths.
You can also see in this photo that "shadcn-svelte" gets wrapped when squished. Also, the github link is being covered by the search bar.
I opted to remove the "GitHub" link, as it could be considered redundant, being that there is a github icon to the right of the search bar. 
I also mimicked the navbar behavior of the shadcn-ui site, to make things line up a little better.
Here is the result after (md):
And (lg):

docs: fix nav link overlapping issues

---

.gitignore

Quick change to ignore any config files generated by JetBrains IDEs

chore: ignore JetBrains IDE config in .gitignore

---

sites/docs/src/lib/registry/default/ui/card/card-content.svelte
sites/docs/src/lib/registry/default/ui/card/card-header.svelte
sites/docs/src/lib/registry/new-york/ui/card/card-content.svelte
sites/docs/src/lib/registry/new-york/ui/card/card-header.svelte

This PR removes bottom padding from the card header instead of removing top padding from the card content. This way, the card content has consistent padding regardless of the presence of a header.
This is symmetrical to how it is done in the card footer.

feat: Make card header optional

---

sites/docs/src/lib/registry/default/ui/button/button.svelte
sites/docs/src/lib/registry/new-york/ui/button/button.svelte

When passing an href to the Button Component, the button does not redirect to the href on click. It appears that {...restProps} doesn't contain the href passed. 
Manually passed the href variable onto the a tag and links work as expected.

fix: Next Button Component with href

---

pnpm-lock.yaml
sites/docs/package.json
sites/docs/src/lib/registry/default/block/dashboard-02.svelte
sites/docs/src/lib/registry/default/block/dashboard-05.svelte
sites/docs/src/lib/registry/default/block/dashboard-06.svelte
sites/docs/src/lib/registry/default/block/dashboard-07.svelte
sites/docs/src/lib/registry/new-york/block/dashboard-02.svelte
sites/docs/src/lib/registry/new-york/block/dashboard-05.svelte
sites/docs/src/lib/registry/new-york/block/dashboard-06.svelte
sites/docs/src/lib/registry/new-york/block/dashboard-07.svelte

Updates `lucide-svelte` to the latest version. Fixes #1212.
I only updated the `docs` package. I'm not sure how the `playground-*` packages are used, if at all - the `playground-js` package uses an even more outdated version while the `playground-ts` package doesn't use it at all.

docs: fix renamed lucide icons

---

.changeset/twelve-files-allow.md
packages/cli/src/commands/add.ts
packages/cli/src/commands/init.ts
packages/cli/src/commands/update.ts
packages/cli/test/commands/init.spec.ts

cli: install dependencies as dev deps

---

.gitignore

Ignoring registry because it unnecessarily bogs down PRs. We build the registry during the site build and CI, so no reason to have its history cluttering our diffs.

next(chore): update `.gitignore`

---

sites/docs/src/lib/registry/default/ui/carousel/context.ts
sites/docs/src/lib/registry/default/ui/drawer/drawer-footer.svelte
sites/docs/src/lib/registry/default/ui/form/form-element-field.svelte
sites/docs/src/lib/registry/default/ui/form/form-field.svelte
sites/docs/src/lib/registry/new-york/ui/carousel/context.ts
sites/docs/src/lib/registry/new-york/ui/drawer/drawer-footer.svelte
sites/docs/src/lib/registry/new-york/ui/form/form-field.svelte

I was planning to create a bunch of types helpers and add them to the `utils.ts` file, but to avoid blurring the lines too much, I think it's best we just stick to the provided Svelte types everywhere. Perhaps we change our mind later given there is a request for it.
This cleans up some remaining leftovers.

next: Fix various elements to use Svelte types vs internal

---

packages/cli/src/utils/templates.ts
pnpm-lock.yaml
sites/docs/package.json
sites/docs/scripts/build-registry.ts
sites/docs/scripts/transformers.ts
sites/docs/src/__registry__/index.js
sites/docs/src/lib/registry/default/ui/data-table/flex-render.svelte
sites/docs/src/lib/registry/default/ui/data-table/render-helpers.ts
sites/docs/src/lib/registry/default/ui/sidebar/context.svelte.ts
sites/docs/src/lib/registry/new-york/ui/data-table/flex-render.svelte
sites/docs/src/lib/registry/new-york/ui/data-table/render-helpers.ts
sites/docs/src/lib/registry/new-york/ui/sidebar/context.svelte.ts
sites/docs/tsconfig.json

fix: properly strip types for JS registry

---

sites/docs/src/content/installation/astro.md

> #### Add TailwindCSS to your project
> Answer `Yes` to all the question prompted by the CLI when installing **Svelte**.
> #### Add TailwindCSS to your project
> Answer `Yes` to all the question prompted by the CLI when installing **TailwindCSS**.
Plus changing the Astro's questions order.

docs: fix tailwind typo

---

sites/docs/src/content/installation/manual.md
sites/docs/src/content/installation/sveltekit.md
sites/docs/src/content/installation/vite.md

Reason: `svelte-add` is now [deprecated](https://github.com/svelte-add/svelte-add/pull/559) and merged with [svelte cli](https://github.com/sveltejs/cli) (`sv`)

docs: replace `svelte-add` with svelte cli

---

sites/docs/src/lib/components/docs/copy-button.svelte
sites/docs/src/lib/registry/new-york/example/breadcrumb-dropdown.svelte
sites/docs/src/lib/registry/new-york/example/breadcrumb-separator.svelte
sites/docs/src/lib/registry/new-york/ui/breadcrumb/breadcrumb-ellipsis.svelte

Not sure why this wasn't errant before, but in a new scaffold, I was getting this error:
```
Type 'string' is not assignable to type 'number'.
```
Happy to close if this leads to unexpected side effects.
P.S. I was using `"svelte-radix": "^2.0.1"` not `"svelte-radix": "2.0.0-next.5"` maybe that's where the mismatch was coming from 🤷

fix: update tabindex attributes to use numbers

---

sites/docs/src/content/components/date-picker.md

For the first;
```
Object literal may only specify known properties, and '"openFocus"' does not exist in type 'PopoverRootPropsWithoutHTML'.ts(2353)
```
The second (because `type` isn't specified);
```
Type 'DateValue | undefined' is not assignable to type 'DateValue[] | undefined'.
Type 'CalendarDate' is missing the following properties from type 'DateValue[]': length, pop, push, concat, and 35 more.ts(2322)
```

docs: update DatePicker/Popover usage example

---

sites/docs/src/lib/registry/default/ui/select/select-scroll-down-button.svelte

The `chevron-up` icon was being imported instead of the `chevron-down` icon

fix: wrong icon import for `ScrollDownButton` in `Select`

---

sites/docs/src/lib/registry/default/example/card-with-form.svelte

solves issue #1424 
- fixes selected showing `[object object]` instead of the actual name of the selected framework when using the `Default` style
Before:
After:

docs: fix card select showing [object object]

---

sites/docs/src/content/components/select.md
sites/docs/src/lib/registry/default/example/cards/payment-method.svelte
sites/docs/src/lib/registry/new-york/example/cards/payment-method.svelte
sites/docs/src/lib/registry/new-york/ui/select/select-trigger.svelte
sites/docs/src/routes/(app)/examples/cards/(components)/payment-method.svelte

next: docs cleanup

---

sites/docs/src/lib/registry/default/example/table-demo.svelte
sites/docs/src/lib/registry/default/ui/table/table-footer.svelte
sites/docs/src/lib/registry/new-york/example/table-demo.svelte
sites/docs/src/lib/registry/new-york/ui/table/table-footer.svelte

Fixes #1440 
- Also syncs the table example with the [shadcn-ui](https://ui.shadcn.com/docs/components/table) table example that way we can notice this more easily.

fix(next): Fix `<Table.Footer>` foreground color

---

.changeset/loud-flies-smoke.md
.changeset/tricky-trains-suffer.md
packages/cli/src/commands/update.ts
packages/cli/src/utils/registry/index.ts
packages/cli/test/utils/registry/index.spec.ts

If you ran `npx shadcn-svelte@next update` before you would notice that even though it completes successfully it doesn't actually update the code for any components.
PS: This sounds super rude reading it back but I can't think of a better way to word it so it's really not intentional
+ Also Closes #1368

fix(next): Update command doesn't update component code

---

sites/docs/src/content/components/data-table.md

I noticed the DataTableProps was likely typo named `DateTableProps` instead of `DataTableProps`. This of course worked fine, but broke when I 'fixed' it when first copy pasting (thinking I had done the typo), so likely just best to keep the name consistent with what someone might expect.

docs: Typo in next data table docs

---

pnpm-lock.yaml
sites/docs/package.json
sites/docs/src/content/components/data-table.md
sites/docs/src/lib/registry/default/example/cards/data-table.svelte
sites/docs/src/lib/registry/default/example/data-table-demo.svelte
sites/docs/src/lib/registry/default/ui/checkbox/checkbox.svelte
sites/docs/src/lib/registry/default/ui/context-menu/context-menu-checkbox-item.svelte
sites/docs/src/lib/registry/default/ui/dropdown-menu/dropdown-menu-checkbox-item.svelte
sites/docs/src/lib/registry/default/ui/menubar/menubar-checkbox-item.svelte
sites/docs/src/lib/registry/new-york/example/cards/data-table.svelte
sites/docs/src/lib/registry/new-york/example/data-table-demo.svelte
sites/docs/src/lib/registry/new-york/ui/checkbox/checkbox.svelte
sites/docs/src/lib/registry/new-york/ui/context-menu/context-menu-checkbox-item.svelte
sites/docs/src/lib/registry/new-york/ui/dropdown-menu/dropdown-menu-checkbox-item.svelte
sites/docs/src/lib/registry/new-york/ui/menubar/menubar-checkbox-item.svelte

Adjusts various `Checkbox` components to handle `indeterminate` state in the new way introduced by Bits UI (reference: https://github.com/huntabyte/bits-ui/pull/898)

next(breaking): update bits & adjust checkbox `indeterminate`

---

sites/docs/scripts/registry.ts

Looks like [1.1.1](https://github.com/shinokada/svelte-radix/releases/tag/v1.1.1) is the latest version of radix for svelte 4.
P.S. I think the registry needs to be built but the build is broken on windows (I only have access to a windows machine rn) so you may need to build and commit.

fix: Pin svelte-radix version for Svelte 4 support

---

.changeset/young-wombats-prove.md
packages/cli/src/utils/get-config.ts

All files generated from `templates.ts` end with a newline. `components.json` should, too.

fix(next): add newline to end of components.json

---

.changeset/ten-spiders-do.md
packages/cli/src/utils/sveltekit.ts

Fixes #1486. 
Sorry about the misunderstanding I skipped like 2 words reading the issue and totally threw me off.

fix(next): resolve command for sveltekit sync as `execute-local`

---

sites/docs/src/content/migration/svelte-5/index.md

This broke the transition, since the bits-ui variable uses a different prefix.

docs: Fixed accordion variable names in migration guide

---

sites/docs/src/lib/registry/new-york/ui/radio-group/radio-group.svelte

Fixes `TypeError: Cannot redefine property: class` when imported

fix: Errors when importing Radio Group

---

pnpm-lock.yaml
sites/docs/package.json
sites/docs/src/lib/registry/default/ui/command/command-input.svelte
sites/docs/src/lib/registry/default/ui/input/input.svelte
sites/docs/src/lib/registry/default/ui/textarea/textarea.svelte
sites/docs/src/lib/registry/new-york/ui/command/command-input.svelte
sites/docs/src/lib/registry/new-york/ui/input/input.svelte
sites/docs/src/lib/registry/new-york/ui/textarea/textarea.svelte

Fixes #1548 
- Updates `<Textarea/>`, `<Input/>`, and `<Command.Input/>` to use the same styles used in the [shadcn/ui commit](https://github.com/shadcn-ui/ui/commit/13c97acf9f6db4b3e89ec8943b6d4463dc575f85#diff-bccc7161022356d1158e1a6412faf48bbe0c296d0b2aa6146418e9dc582c8901R7)
- Bumps bits-ui -> `next.71`
P.S. `<Command.Input/>` isn't in that original commit but I think it should be added anyways since it will cause the same issue

fix: Update text sizes in inputs for improved Safari support

---

sites/docs/scripts/registry.ts
sites/docs/scripts/tmp.ts

As we release new majors for dependencies that only support Svelte 5, we'll pin those dependencies to their latest Svelte 4-supported version.

registry: pin deps

---

sites/docs/scripts/registry.ts

Fixes #1534 
The root of #1534 was actually that the `index.json` and `button.json` files did not include `bits-ui` as a dependency. With a little (a lot more than I am proud of) digging I figured out that we aren't parsing the `<script module>` tags in `.svelte` files. (I did this same thing in my own project need to go fix that now).
This PR adds second walk of the `<script module>` tag if it exists so that we catch all the imports.

fix(next): parse `<script module>` tags for imports

---

sites/docs/scripts/tmp.ts

Formsnap v2 has been released so we no longer need to install the `@next` release and can just rely on `latest` for Svelte 5 😃

next: use `formsnap@latest`

---

sites/docs/src/lib/registry/default/example/combobox-demo.svelte

The current default example:
The new york example works fine since it doesn't have the `ml-auto`.
This PR just removes the `ml-auto` class.

docs(next): Fix combobox example text alignment

---

sites/docs/src/content/migration/svelte-5/index.md

* replaced `\\` with `/` in code example under `components.json`. (see screenshot)
* on `https://next.shadcn-svelte.com/docs/migration/svelte-5`
* Shown on website as: `"css": "src\app.pcss",` (should be '/')

Typo: docs-migration-svelte-5,  replaced \\ with /

---

sites/docs/src/content/installation/vite.md

In the latest version of Vite, tsconfig.json has been split into three parts.
- tsconfig.app.json
- tsconfig.json
- tsconfig.node.json
Both tsconfig.app.json and tsconfig.json need to configure path aliases. In fact, the React version of shadcn/ui has already fixed this issue, so the documentation error also needs to be fixed in the Svelte version.

docs: Update the installation documentation for svelte shadcn/ui when using vite.

---

sites/docs/src/lib/registry/default/ui/range-calendar/range-calendar-cell.svelte

Resolves https://github.com/huntabyte/shadcn-svelte/issues/1587

fix: disable bg-accent from range-calendar-cell when it is the highlighted element

---

sites/docs/src/lib/components/docs/pm-install.svelte

Fixes #1614 
I know I will have to fix this in some of my other projects as well 🤦

docs(next): use `add` instead of `install` for `<PMInstall/>`

---

sites/docs/src/lib/registry/new-york/ui/command/command-link-item.svelte

Command.Item had the new css for svg icons, but Command.LinkItem didn't.

fix: added svg css to command-link-item

---

sites/docs/src/content/components/form.md

fix(docs): Pass `data` instead of `form.data`

---

sites/docs/src/lib/registry/default/hook/is-mobile.svelte.ts
sites/docs/src/lib/registry/new-york/hook/is-mobile.svelte.ts

- Fixes code redundancy.
- Does not introduce breaking changes for dependent components.
- Introduces breaking change when using `svelte` version older than `5.7.0`.
- Addresses #1615.
Hey, since the Svelte team added the [`MediaQuery`](https://svelte.dev/docs/svelte/svelte-reactivity#MediaQuery) class, the `IsMobile` hook is now somewhat redundant. 
To keep compatibility with all dependent components, the `IsMobile` class still exists but extends the `MediaQuery` class, which provides the same functionality.

fix(next): update `is-mobile` hook to use new `MediaQuery` class

---

sites/docs/src/content/installation/vite.md
sites/docs/src/lib/components/docs/pm-install.svelte

The `pnpm add` in the current document is not a valid command and should be changed to `pnpm i` to install dependencies.
Before
After

docs: update install command

---

sites/docs/src/content/installation/manual.md
sites/docs/src/content/installation/sveltekit.md
sites/docs/src/content/installation/vite.md

Fixes #1671 
Pins the `sv` version to the latest version supporting tailwind v3 (`0.6.18`)

docs(next): pin `sv` version

---

sites/docs/src/lib/registry/default/example/cards/team-members.svelte

fix: removed duplicate avatar on themes page

---

.github/workflows/build-preview.yml
.github/workflows/deploy-prod.yml
sites/docs/src/content/installation/manual.md
sites/docs/src/content/installation/sveltekit.md
sites/docs/src/content/installation/vite.md
sites/docs/src/lib/registry/default/ui/sheet/index.ts
sites/docs/src/lib/registry/new-york/ui/sheet/index.ts

chore: pin sv version and remove unnecessary installation step

---

sites/docs/src/lib/registry/default/ui/input/input.svelte
sites/docs/src/lib/registry/new-york/ui/input/input.svelte

Fixes #1524 
With a little bit of type gymnastics we are able to make this work.
A few examples:
```svelte
<Input type="file" bind:files />
```
```svelte
<Input />
```
```svelte
<Input type="search" />
```
```svelte
<Input type="text" bind:files/>
```
```svelte
<Input bind:files />
```

feat: Allow `bind:files` on input component

---

sites/docs/src/lib/registry/default/ui/avatar/avatar-fallback.svelte
sites/docs/src/lib/registry/default/ui/avatar/avatar-image.svelte
sites/docs/src/lib/registry/new-york/ui/avatar/avatar-fallback.svelte
sites/docs/src/lib/registry/new-york/ui/avatar/avatar-image.svelte

This PR removes the rounded-full class from the avatar-fallback implementation. 
Since we are already using overflow-hidden on `<Avatar.Root/>` there isn't really any reason this should be rounded especially since it can cause issues like the following:
```svelte
<Avatar.Root class="rounded-md">
<Avatar.Image src=""/>
<Avatar.Fallback>
<Upload/>
</Avatar.Fallback>
</Avatar.Root>
```
Went ahead and also changed the sizing classes to use size-full instead of w and h.

fix(next): remove rounded-full from avatar-fallback + use size instead of w and h

---

sites/docs/src/content/migration/svelte-5/index.md

Related: https://github.com/huntabyte/shadcn-svelte/issues/1718#issuecomment-2677279768 (Since it's morning for me before you, @ieedan 😅 )

fix(docs): update bits-ui installation command in migration guide

---

.changeset/sweet-steaks-teach.md
packages/cli/src/utils/registry/index.ts

This PR adds a temporary workaround to the CLI to prevent further disruption. If a user is looking to hit `https://next.shadcn-svelte.com/registry` as their registry base URL, we instead point them to the true cloudflare preview domain `https://huntabyte-next.shadcn-svelte.pages.dev/registry` to circumvent some odd caching issues that recently arose with CloudFlare.
For anyone curious, CloudFlare seems to be serving the static assets from the root site (shadcn-svelte.com) instead of next.shadcn-svelte.com, regardless of what is being hit via curl/fetch, causing schema validation issues with the CLI. This just started happening recently.
Closes #1726

fix: registry tree fetch

---

sites/docs/src/lib/registry/default/block/demo-sidebar-footer.svelte
sites/docs/src/lib/registry/default/block/demo-sidebar-header.svelte
sites/docs/src/lib/registry/default/block/sidebar-01/components/version-switcher.svelte
sites/docs/src/lib/registry/default/block/sidebar-02/components/version-switcher.svelte
sites/docs/src/lib/registry/default/block/sidebar-07/components/nav-user.svelte
sites/docs/src/lib/registry/default/block/sidebar-07/components/team-switcher.svelte
sites/docs/src/lib/registry/default/block/sidebar-08/components/nav-user.svelte
sites/docs/src/lib/registry/default/block/sidebar-09/components/nav-user.svelte
sites/docs/src/lib/registry/default/block/sidebar-12/components/nav-user.svelte
sites/docs/src/lib/registry/default/block/sidebar-15/components/nav-user.svelte
sites/docs/src/lib/registry/default/ui/sidebar/sidebar-menu-skeleton.svelte
sites/docs/src/lib/registry/default/ui/sidebar/sidebar.svelte
sites/docs/src/lib/registry/new-york/block/demo-sidebar-footer.svelte
sites/docs/src/lib/registry/new-york/block/demo-sidebar-header.svelte
sites/docs/src/lib/registry/new-york/block/sidebar-01/components/version-switcher.svelte
sites/docs/src/lib/registry/new-york/block/sidebar-02/components/version-switcher.svelte
sites/docs/src/lib/registry/new-york/block/sidebar-07/components/nav-user.svelte
sites/docs/src/lib/registry/new-york/block/sidebar-07/components/team-switcher.svelte
sites/docs/src/lib/registry/new-york/block/sidebar-08/components/nav-user.svelte
sites/docs/src/lib/registry/new-york/block/sidebar-09/components/nav-user.svelte
sites/docs/src/lib/registry/new-york/block/sidebar-12/components/nav-user.svelte
sites/docs/src/lib/registry/new-york/block/sidebar-15/components/nav-user.svelte
sites/docs/src/lib/registry/new-york/ui/sidebar/sidebar-menu-skeleton.svelte
sites/docs/src/lib/registry/new-york/ui/sidebar/sidebar.svelte

In some of the computed classes (but not most of them) `var()` is missing around the CSS variable.

fix missing var()

---

pnpm-lock.yaml
sites/docs/package.json
sites/docs/src/content/components/dropdown-menu.md
sites/docs/src/lib/components/docs/copy-button.svelte
sites/docs/src/lib/components/docs/hex-to-channels.svelte
sites/docs/src/lib/components/docs/markdown/pre.svelte
sites/docs/src/lib/components/docs/pm-block.svelte
sites/docs/src/lib/hooks/use-clipboard.svelte.ts
sites/docs/src/lib/stores/package-manager.ts

Updates the `<PMBlock/>` to use the style of the original. 
This also decouples the code for `<Pre/>` and `<CopyButton/>` from the `<PMBlock/>`.

docs(next): Update PM Block

---

.changeset/flat-sloths-learn.md
packages/cli/src/commands/init.ts

Adds missing option `--ui-alias <path>` to CLI
This would allow a non-interactive initialization:
```bash
pnpm dlx shadcn-svelte@next init \
--style default \
--base-color slate \
--css src/app.css \
--tailwind-config tailwind.config.ts \
--components-alias '$lib/components' \
--utils-alias '$lib/utils' \
--hooks-alias '$lib/hooks' \
--ui-alias '$lib/components/ui'
```

fix(cli)(next): add missing ui alias option

---

sites/docs/src/lib/registry/ui/tooltip/index.ts

Fixes #1779 
I am gonna open this on the v4 version to make sure there aren't any conflicts and that the changes make it through. The changes are simple enough that those that need this can use this PR for reference.

fix: Export `Portal` component from Tooltip

---

sites/docs/src/lib/registry/default/ui/slider/slider.svelte
sites/docs/src/lib/registry/new-york/ui/slider/slider.svelte

This PR adds a key to the each-block of slider, which resolves this lint error
https://sveltejs.github.io/eslint-plugin-svelte/rules/require-each-key/
That lint rule (or the inclusion of the rule) was added in eslint-plugin-svelte v3 (which this project doesn't yet use).

fix(slider): add missing each-key

---

sites/docs/src/lib/registry/themes.ts

Fixes #1799 for v4 follow up to #1804

fix(v4): Remove extra semi from generated themes

---

sites/docs/src/content/dark-mode/astro.md
sites/docs/src/content/dark-mode/svelte.md

We're about to release mode-watcher 1.0 which will be for Svelte 5 only, so pinning 0.5 to the Svelte 4 shadcn-svelte doc install guide.

docs: pin mode watcher to 0.5

---

sites/docs/src/content/components-json.md
sites/docs/src/content/dark-mode/svelte.md
sites/docs/src/styles/globals.css

Fixes #1823
- Fixes `<Steps/>` so that the numbers show up next to the headings again
- Removes `tailwind.config` section of docs since we don't use it anymore

chore(v4): Docs fixes

---

sites/docs/src/lib/registry/ui/button/button.svelte

Forgot to downstream this from `bits-ui` before and found myself needing it so I thought I would come and add it here.
bits-ui PR: https://github.com/huntabyte/bits-ui/pull/1055

feat(v4): Allow buttons with href to be disabled

---

sites/docs/src/content/components/data-table.md
sites/docs/src/lib/registry/default/example/cards/data-table.svelte
sites/docs/src/lib/registry/default/example/data-table-demo.svelte
sites/docs/src/lib/registry/new-york/example/cards/data-table.svelte
sites/docs/src/lib/registry/new-york/example/data-table-demo.svelte

This uses `column.getToggleSortingHandler()` instead of `() => column.toggleSorting(column.getIsSorted() === "asc")`.
The main difference here is that getToggleSortingHandler honors settings such as `sortDescFirst`. I verified that this works better in my own project.
Reference: https://tanstack.com/table/latest/docs/guide/sorting#sorting-apis
Closes #1857

docs: Use recommended onclick sorting handler in data-table sorting section

---

sites/docs/src/lib/registry/default/ui/command/command-link-item.svelte

fix(Command): ensure `LinkItem` and `Item` styles are consistent

---

sites/docs/src/lib/components/docs/pm-block.svelte
sites/docs/src/styles/markdown.css

This will fix some problems in #1770 docs.
Light theme CLI command is invisible.
Fixes by setting background color to `bg-accent/50`.
It works both in light and dark mode. (copied style from current `next`)
| Before | After |
|---|---|
| ![image](https://github.com/user-attachments/assets/d9452639-3eb4-43e7-9c92-ebe056b13088) | ![image](https://github.com/user-attachments/assets/1ac9a3a1-e358-4a9e-a282-ce805b0278ad) |
Highlighted line is invisible, although attiribute is set in html element.
```html
<span class="line--highlighted" data-line="" data-highlighted-line="">
```
Fixed `color-mix()` syntax.
| Before | After |
|---|---|
| ![image](https://github.com/user-attachments/assets/fff8a23a-6fc9-46ea-a5c5-7d18f6dfdbd9) | ![image](https://github.com/user-attachments/assets/6e93142a-17a9-481 …

fix: tw4 docs style

---

packages/cli/src/commands/registry/build.ts
packages/cli/src/constants.ts
packages/cli/src/utils/transformers.ts
packages/cli/test/utils/transformers.spec.ts
packages/registry/src/schemas.ts
sites/docs/registry.json
sites/docs/scripts/build-registry.ts

Adds a transformer to the `shadcn-svelte regsitry build` command that transforms import aliases into a standardized format.
So this:
```js
import Button from "$lib/registry/ui/button/index.js"
import isMobile from "$lib/registry/hooks/is-mobile.svelte.js"
```
would be transformed into this:
```js
import Button from "$UI$/button/index.js"
import isMobile from "$HOOKS$/is-mobile.svelte.js"
```
Aliases can be configured in the `registry.json` schema:
```jsonc
{
"$schema": "...",
"name": "shadcn-svelte",
"aliases": {
"lib": "$lib/registry/lib",
"ui": "$lib/registry/ui",
"components": "$lib/registry/components",
"utils": "$lib/utils",
"hooks": "$lib/registry/hooks"
},
// ...
}
```

feat(tw4-next): transform registry aliases into alias placeholders

---

v4/src/lib/components/card-demo.svelte

This pull request includes a minor fix to the `card-demo.svelte` file to adjust the layout of card components for better responsiveness.
<details>
<summary>before on mobile</summary>
</details>
<details>
<summary>after</summary>
</details>

tw-4: fix cards preview for better responsiveness

---

packages/cli/src/commands/registry/build.ts
packages/registry/src/schemas.ts
sites/docs/src/content/cli.md
sites/docs/src/content/registry/registry-item-json.md
sites/docs/src/content/registry/registry-json.md

tw4: registry cli docs

---

sites/docs/registry.json
sites/docs/src/content/changelog.md
sites/docs/src/content/components-json.md
sites/docs/src/content/migration/svelte-5.md
sites/docs/src/content/migration/tailwind-v4.md
sites/docs/src/content/registry/getting-started.md
sites/docs/src/content/registry/index.md
sites/docs/src/lib/config/docs.ts

It's a bit much to expect users to go straight from Svelte v4 and Tailwind v3 -> Svelte v5 and Tailwind v4 (speaking from experience here), so we've added specific guides for:
With the idea being you can incrementally go into Svelte 5 and Tailwind 3 and then when ready bump the Tailwind version.
- Svelte v4 and Tailwind v3 -> Svelte v5 and Tailwind v3
- Svelte v5 and Tailwind v3 -> Tailwind v4

docs(tw4): migration docs

---

packages/cli/src/commands/registry/build.ts
packages/cli/src/commands/update/index.ts
packages/cli/src/utils/add-registry-items.ts
packages/cli/src/utils/registry/index.ts
registry-template/registry.json
sites/docs/src/content/registry/registry-item-json.md
sites/docs/src/content/registry/registry-json.md

Enables custom registries to reference their own components as `registryDependencies` using the `local:<item_name>` shorthand, which resolves to a relative path that we use to grab it.

feat(cli): `local:` registryDeps

---

sites/docs/src/content/cli.md
sites/docs/src/content/migration/tailwind-v4.md
sites/docs/src/content/registry/getting-started.md
sites/docs/src/content/registry/index.md
sites/docs/src/styles/markdown.css

A few things I found going through the docs.

docs(twv4): Review registry docs

---

packages/cli/src/commands/init/preflight.ts
packages/cli/test/utils/preflight-init.test.ts
v4/src/lib/registry/charts/chart-bar-negative.svelte
v4/src/lib/registry/charts/chart-line-dots.svelte
v4/src/lib/registry/charts/chart-radar-lines-only.svelte
v4/src/lib/registry/ui/pagination/pagination-link.svelte
v4/src/lib/registry/ui/pagination/pagination-next-button.svelte

tw4: cleanup/improve error messaging

---

packages/cli/src/commands/init/index.ts
packages/cli/src/commands/init/preflight.ts
packages/cli/src/utils/get-config.ts
packages/cli/test/utils/preflight-init.test.ts

chore(tw4): cli fixes and tweaks

---

sites/docs/src/lib/registry/ui/calendar/calendar-day.svelte
sites/docs/src/lib/registry/ui/range-calendar/range-calendar-day.svelte

This pull request includes an update to the `calendar-day.svelte` component to fix its behavior in dark mode. Before, hovering on the selected day in dark mode would display `bg-accent/50` due to the `"ghost"` variant of `Button`.
---
Added `dark:data-selected:hover:bg-primary` and `dark:data-selected:focus:bg-primary` to the `data-selected` styling.

fix(calendar-day): enhance dark mode styles for selected state

---

packages/registry/src/schemas.ts
sites/docs/scripts/build-registry.ts
sites/docs/src/content/components-json.md
sites/docs/static/schema.json
sites/docs/vite.config.ts

chore(tw4): add `components.json` schema descriptions

---

sites/docs/src/content/migration/svelte-5.md

docs(next): Update `utils.ts` in svelte 5 migration

---

sites/docs/src/content/migration/tailwind-v4.md

Fixes #1991 
We could keep update but we'd have to remove `@latest` this just changes it to use install like the rest of the docs.

docs(next): Use `install` instead of `update` in tailwind migration docs

---

sites/docs/src/lib/registry/ui/tooltip/tooltip-content.svelte

This pull request updates the tooltip alignment logic in `tooltip-content.svelte` to use `data-*` attributes for conditional styling instead of JavaScript-based conditional classes. This change simplifies the code and improves maintainability.
Styling improvements:
* [`sites/docs/src/lib/registry/ui/tooltip/tooltip-content.svelte`](diffhunk://#diff-b63e09bd98361a0f403080d9e129ce647b015358f8e7c01583bc0ef16c951994L36-R39): Replaced conditional class logic based on `side` with `data-*` attributes for styling, enabling the styles to adapt as the tooltip content flips due to spacing limitations

fix(Tooltip): use `data-side` attrs

---

sites/docs/src/content/components/pagination.md

closes #1681
This is just a documentation error. `isVisible` is not a valid prop in `Pagination.Item`.

docs: remove `isVisible` from Pagination usage

---

sites/docs/src/lib/registry/ui/drawer/drawer-content.svelte
sites/docs/src/lib/registry/ui/drawer/drawer-footer.svelte
sites/docs/src/lib/registry/ui/drawer/drawer-header.svelte

This PR updates the drawer padding to be more consistent with the way that the dialog header and footer works.
It's worth noting that this is NOT how the original is styled. But to me it makes more sense this way.

fix(next): Drawer padding consistency

---

sites/docs/src/content/components/sonner.md
sites/docs/src/content/installation/astro.md
sites/docs/src/content/installation/manual.md
sites/docs/src/content/installation/sveltekit.md
sites/docs/src/content/installation/vite.md
sites/docs/src/content/migration/tailwind-v4.md
sites/docs/src/content/registry/getting-started.md

https://github.com/huntabyte/shadcn-svelte/pull/1848

fix (next): "set up" as verb

---

docs/src/lib/components/block-viewer-copy-code-button.svelte

fix(next): transform import paths for copied content in block viewer

---

.changeset/fine-drinks-marry.md
packages/cli/src/commands/update/index.ts
registry-template/src/lib/registry/ui/card/card-footer.svelte
registry-template/src/lib/registry/ui/card/card-header.svelte
registry-template/src/lib/registry/ui/card/card-title.svelte
registry-template/src/lib/registry/ui/input/input.svelte
registry-template/src/lib/registry/ui/label/label.svelte
registry-template/src/lib/registry/ui/textarea/input.svelte

`Dirent.path` is deprecated since Node 20.12.0, and has been replaced since then by `Dirent.parentPath`, which is essentially an alias.
`Dirent.path` seems to have been removed in Node 24, breaking for most recent Node versions in a similar way to #1003.
As shadcn-svelte officially only supports Node 22+, I think it's fair to replace the usage completely.
This is the only instance of `Dirent.path` I found throughout the entire codebase.

fix(cli): update failing on recent Node versions

---

.changeset/many-forks-train.md
packages/cli/src/commands/update/index.ts
registry-template/src/lib/registry/ui/card/card-footer.svelte
registry-template/src/lib/registry/ui/card/card-header.svelte
registry-template/src/lib/registry/ui/card/card-title.svelte
registry-template/src/lib/registry/ui/input/input.svelte
registry-template/src/lib/registry/ui/label/label.svelte
registry-template/src/lib/registry/ui/textarea/input.svelte

Missing directories should be ignored rather than causing an error. I, for example, don't have any hooks, so no `hooks` directory. When I want to update my components, the CLI throws because it wants an empty directory instead of just ignoring it. This PR fixes that.
I didn’t encounter any issues after making this change, so it's safe to do as far as I’m aware.
~~Due to previous lint issues in `registry-template`, #2087 must be merged before this one.~~

fix(cli): skip missing directories instead of throwing

---

docs/src/lib/components/command-menu/command-menu.svelte

Fix useMac and add `current`.
If you're using windows, it does not display `ctrl` instead of `⌘` in the search bar.  The `useMac` custom hook does not correctly reference the `current` method.

fix: Update command-menu.svelte - useMac

---

docs/src/lib/registry/ui/tooltip/tooltip-content.svelte

Fixes the alignment of tooltip arrows when `side="bottom"` or `side="left"`.
Closes #2165

fix: tooltip arrow alignment when side is bottom or left

---

docs/src/lib/registry/ui/sidebar/sidebar-rail.svelte

The `<Sidebar.Rail />` visual element was not centered with its corresponding DOM element.
This fixes it.
(Closes https://github.com/huntabyte/shadcn-svelte/issues/2170)

fix: center `<Sidebar.Rail />` visual element

---

docs/src/lib/registry/ui/table/table-cell.svelte
docs/src/lib/registry/ui/table/table-head.svelte
docs/src/lib/registry/ui/table/table-row.svelte

When hovering over a `<Table.Row>` the highlight would be seen under the row borders.
(Exaggerating border with `[&_tr]:border-b-8`)
Actual:
Expected:
To fix this, I had to move the highlight from the row to the cells.
The `... :[&,&>svelte-css-wrapper]: ...` selector is to handle the case where you define a CSS variable in a `<Table.Head>` or `<Table.Cell>`, like:
```svelte
<Table.Row>
<Table.Cell --css-var={someReactiveVar}>
Row
</Tabel.Cell>
</Table.Row>
```
which would result in this HTML structure:
```html
<tr>
<svelte-css-wrapper>
<td>
Row
</td>
</svelte-css-wrapper>
</tr>
```

fix: `<Table.Row>` highlight no longer under the row borders

---

docs/src/lib/registry/ui/sidebar/sidebar.svelte

The `<Sidebar.Root>` gap `<div>` doesn't have the same dimensions as the `<Sidebar.Root>` `<div>` when the sidebar is floating/inset and collapsed into icons.
Code for reference:
Closes: https://github.com/huntabyte/shadcn-svelte/issues/2169
(Didn't have any feedback, but since it's a small fix, I decided to create a PR)

fix: `<Sidebar.Root>` gap width now same as `<Sidebar.Root>` width

---

docs/src/lib/registry/ui/chart/chart-style.svelte

The `Chart` component was using this old syntax:
```tsx
{@html `<style>${themeContents}</style>`}
```
making the error `Unknown word themeContents` raise.
I fixed it by using the `<svelte:element this={'style'}>` component instead of the raw `@html`
Discord thread: https://discord.com/channels/1194404141389336576/1393230690245541949

fix: Use svelte:element instead of @html

---

docs/src/lib/components/chart-toolbar.svelte

Fixes #2258
This PR resolves a bug where the **"Copy"** button in the chart toolbar
always copied the code from the **first chart opened** on the page,
regardless of the chart currently being viewed.
1. Open a chart page (e.g. *Area Chart – Interactive*).
2. Click **View Code** → correct code is displayed.
3. Click **Copy** → correct code is copied for this chart.
4. Navigate to a different chart (e.g. *Area Chart – Linear*).
5. Click **View Code** → correct code is displayed for the new chart.
6. Click **Copy** → **incorrect**: clipboard still contains code from the first chart.
- Copy logic extracted highlighted HTML **only once** in `onMount` and never
updated when the selected chart or file changed.
- Highlighted HTML contained encoded entities that required decoding before copying.
- …

docs: fix copying the correct source for current chart in chart-toolbar (#2258)

---

docs/src/lib/components/component-code-viewer/component-code-viewer-file-tree.svelte

Closes #2293 
Fix scrollable sidebar group where files in code viewer tree are located under.

fix: make sidebar file tree under group scrollable

---

docs/registry.json
docs/src/lib/registry/blocks/new-components-01/+page.svelte

Fixes the broken new-components-01 block by adding the missing `<Tooltip.Provider>` to `+page.svelte`. 
Checkout the preview build to see the working block. https://icalvin102-fix-new-component.shadcn-svelte.pages.dev/view/new-components-01
Fixes #2322

fix: new-components-01 by adding Tooltip.Provider

---

docs/content/components/empty.md

Updates the correct usage example in the [new Empty ](https://www.shadcn-svelte.com/docs/components/empty#usage)component docs.
Closes: #2324
Edit: updated commit message.

docs: update empty component docs usage example.
