huntabyte/shadcn-svelte

- .changeset/hip-suits-grab.md
- apps/www/.prettierrc
- packages/cli/src/utils/set-config.ts
> chore: add parser to CLI prettier

- .github/workflows/build-components.yml
- apps/www/src/lib/components/ui/button/Button.svelte
> fix: provide correct element attribute types for `Button`

- .changeset/wicked-toys-yawn.md
- packages/cli/src/index.ts
--nodep disables downloading dependencies
> add --nodep flag

- .changeset/chilled-radios-raise.md
- apps/www/tailwind.config.js
- packages/cli/src/index.ts
- packages/cli/src/utils/templates.ts
> fix: Replaced `tailwind.config.cjs` for an ESM config template

- .changeset/healthy-doors-exercise.md
- .changeset/shiny-windows-rule.md
- packages/cli/src/index.ts
> feat: update components command

- apps/www/src/styles/globals.css
> chore: add custom scrollbar & scrollbar gutter

- apps/www/src/routes/+page.svelte
Add a link to the temp component roadmap to the doc site homepage.
> enhancement: add temp component roadmap announcement

- apps/www/src/content/components/sheet.md
Fix incorrect import path in Sheet documentation.
> Fix Sheet documentation

- apps/www/src/lib/registry/default/ui/card/card-title.svelte
- apps/www/src/lib/registry/new-york/ui/card/card-title.svelte
> fix: card title import

- apps/www/src/content/components-json.md
- apps/www/src/content/installation.md
> improve install/components.json docs

- apps/www/package.json
- apps/www/pnpm-lock.yaml
- apps/www/src/lib/registry/default/ui/menubar/menubar-checkbox-item.svelte
- apps/www/src/lib/registry/default/ui/menubar/menubar-item.svelte
- apps/www/src/lib/registry/default/ui/menubar/menubar-radio-item.svelte
- apps/www/src/lib/registry/new-york/ui/menubar/menubar-checkbox-item.svelte
- apps/www/src/lib/registry/new-york/ui/menubar/menubar-item.svelte
- apps/www/src/lib/registry/new-york/ui/menubar/menubar-radio-item.svelte
> Forward menubar item click events

- apps/www/src/lib/registry/default/ui/table/table-cell.svelte
- apps/www/src/lib/registry/default/ui/table/table-head.svelte
- apps/www/src/lib/registry/new-york/ui/table/table-cell.svelte
- apps/www/src/lib/registry/new-york/ui/table/table-head.svelte
> fix: table cell and head types

- apps/www/src/lib/registry/default/example/input-with-label.svelte
- apps/www/src/lib/registry/default/example/input-with-text.svelte
fixes #252
This pull request fixes the wrong layout displayed in the docs as stated in the issue above.
> Input layout fix

- apps/www/src/lib/config/docs.ts
Fixes [246](https://github.com/huntabyte/shadcn-svelte/issues/246)
> Updated example 'View code' links for Playground and Music

- apps/www/src/content/components/collapsible.md
> changed "radix-svelte" to "bits-ui" in collapsible.md

- apps/www/src/lib/registry/default/ui/form/form-description.svelte
- apps/www/src/lib/registry/default/ui/form/form-item.svelte
- apps/www/src/lib/registry/default/ui/form/form-label.svelte
- apps/www/src/lib/registry/default/ui/form/form-native-select.svelte
- apps/www/src/lib/registry/default/ui/form/form-validation.svelte
> Fixed the import path for `utils`

- apps/www/src/content/components/form.md
- apps/www/src/lib/registry/default/ui/alert-dialog/alert-dialog-action.svelte
- apps/www/src/lib/registry/default/ui/alert-dialog/alert-dialog-cancel.svelte
> forward events for alert dialog

- apps/www/src/lib/registry/default/ui/button/index.ts
- apps/www/src/lib/registry/new-york/ui/button/index.ts
This fixes #272 
Edit: Realised my mistake that i should have waited on your @huntabyte  acceptance before making this PR.
> Added whitespace-nowrap to button base

- apps/www/src/lib/registry/new-york/ui/form/form-description.svelte
- apps/www/src/lib/registry/new-york/ui/form/form-item.svelte
- apps/www/src/lib/registry/new-york/ui/form/form-label.svelte
- apps/www/src/lib/registry/new-york/ui/form/form-native-select.svelte
- apps/www/src/lib/registry/new-york/ui/form/form-validation.svelte
- apps/www/static/registry/styles/new-york/form.json
> fixed `utils` import for the new york style

- apps/www/src/content/components/slider.md
> fix: slider docs typo

- apps/www/src/lib/components/docs/theme-customizer/customizer.svelte
about [this](https://github.com/huntabyte/shadcn-svelte/issues/293) issue.
> fixing the typo

- apps/www/src/content/components/card.md
> Docs: Change CardTitle -> Card.Title

- apps/www/src/content/components/toggle.md
- apps/www/static/registry/themes.css
> fix toggle doc code snippets

- apps/www/src/lib/registry/default/example/checkbox-disabled.svelte
- apps/www/src/lib/registry/default/ui/checkbox/checkbox.svelte
- apps/www/src/lib/registry/new-york/example/checkbox-disabled.svelte
- apps/www/src/lib/registry/new-york/ui/checkbox/checkbox.svelte
> Fix disabled checkbox styles

- apps/www/src/lib/registry/default/ui/form/form-select.svelte
- apps/www/src/lib/registry/new-york/ui/form/form-select.svelte
> fix required form select props

- .changeset/calm-pears-sort.md
- packages/cli/src/commands/init.ts
> Update file overwrite warning

- apps/www/src/content/components/data-table.md
Fix for linting problem. Added missing comma in data-table.md doc file.
> Added missing comma in datatable md

- .editorconfig
`"tabs"` is not a valid configuration option for `"indent_style"`.
> Editorconfig indent_style tabs -> tab

- apps/www/src/routes/examples/tasks/(components)/data-table-faceted-filter.svelte
Correct class attribute naming
> fix: tasks filter class attribute name

- apps/www/src/lib/components/docs/nav/main-nav.svelte
> Updated main nav links

- apps/www/src/lib/components/docs/nav/mobile-nav.svelte
> feat: add label field on mobile menu

- .changeset/chilly-cows-draw.md
- apps/www/src/content/cli.md
- apps/www/src/content/components-json.md
- apps/www/src/content/installation.md
- apps/www/src/content/theming.md
- packages/cli/src/commands/init.ts
- packages/cli/src/utils/get-config.ts
> rename extension name from .postcss to .pcss

- apps/www/src/content/components/data-table.md
Data Table doc has incorrect import for Pagination, and hence broken.
> fix incorrect import and broken code in Data Table doc

- apps/www/src/routes/examples/cards/(components)/create-account.svelte
> fix: Brand typo Github to GitHub

- .changeset/forty-jeans-teach.md
- packages/cli/src/commands/add.ts
This should close #273. The changes to the CLI output are the same as those in the 'Expected Behavior' of the above issue.
> feat: Improve CLI output

- apps/www/src/content/changelog.md
- apps/www/src/content/components/sonner.md
> docs: fix sonner links

- apps/www/src/content/components/form.md
> docs: Adjusted Forms documentation to use async/await 

- apps/www/src/content/components/aspect-ratio.md
> docs: import path in aspect-ratio component

- apps/www/package.json
- apps/www/pnpm-lock.yaml
> chore: update bits-ui version

- apps/www/src/content/components/sonner.md
- apps/www/src/content/dark-mode.md
> docs: update links

- apps/www/src/routes/examples/forms/(components)/sidebar-nav.svelte
https://github.com/huntabyte/shadcn-svelte/assets/53095479/95b0e68f-9b85-4599-8d04-f4173838d909
https://github.com/huntabyte/shadcn-svelte/assets/53095479/246b3490-ac39-41a6-b1a4-4c05bdbdb9c4
> docs: fix link scroll jump

- apps/www/src/lib/registry/default/ui/carousel/carousel-next.svelte
- apps/www/src/lib/registry/default/ui/carousel/carousel-previous.svelte
- apps/www/src/lib/registry/new-york/ui/carousel/carousel-next.svelte
- apps/www/src/lib/registry/new-york/ui/carousel/carousel-previous.svelte
> fix: Carousel next and previous button touch action styles

- apps/www/src/app.html
> fix(docs): viewport meta

- apps/www/src/lib/components/docs/copy-button.svelte
> docs: Remove the `--bun` flag from command copy

- .changeset/strange-crabs-provide.md
- apps/www/package.json
- apps/www/pnpm-lock.yaml
- apps/www/src/lib/registry/default/ui/slider/slider.svelte
- apps/www/src/lib/registry/new-york/ui/slider/slider.svelte
> feat: Update `Slider` to latest Bits UI API

- apps/www/src/content/components/data-table.md
> docs: update data-table.md to fix line highlight

- apps/www/src/lib/components/docs/copy-button.svelte
- packages/cli/src/utils/registry/index.ts
******************
This PR converts the `console.log()`s in the `catch` blocks to `console.error()`.
> chore: convert console.log to console.error for visibility

- apps/www/src/content/components/form.md
> docs: fix form typo

- apps/www/__registry__/index.js
- apps/www/src/content/components/checkbox.md
- apps/www/src/content/components/combobox.md
- apps/www/src/lib/registry/default/example/checkbox-form-multiple.svelte
- apps/www/src/lib/registry/default/example/checkbox-form-single.svelte
- apps/www/src/lib/registry/default/example/combobox-form.svelte
- apps/www/src/lib/registry/default/example/date-picker-form.svelte
- apps/www/src/lib/registry/default/example/form-demo.svelte
- apps/www/src/lib/registry/default/example/radio-group-form.svelte
- apps/www/src/lib/registry/default/example/select-form.svelte
- apps/www/src/lib/registry/default/example/switch-form.svelte
- apps/www/src/lib/registry/default/example/textarea-form.svelte
- apps/www/src/lib/registry/default/ui/select/select-item.svelte
- apps/www/src/lib/registry/new-york/example/checkbox-form-multiple.svelte
- apps/www/src/lib/registry/new-york/example/checkbox-form-single.svelte
- apps/www/src/lib/registry/new-york/example/combobox-form.svelte
- apps/www/src/lib/registry/new-york/example/date-picker-form.svelte
- apps/www/src/lib/registry/new-york/example/form-demo.svelte
- apps/www/src/lib/registry/new-york/example/radio-group-form.svelte
- apps/www/src/lib/registry/new-york/example/select-form.svelte
- apps/www/src/lib/registry/new-york/example/switch-form.svelte
- apps/www/src/lib/registry/new-york/example/textarea-form.svelte
- apps/www/src/lib/registry/new-york/ui/select/select-item.svelte
- apps/www/src/routes/docs/[...slug]/+page.server.ts
- apps/www/static/registry/styles/default-js/form.json
- apps/www/static/registry/styles/default/form.json
- apps/www/static/registry/styles/new-york-js/form.json
- apps/www/static/registry/styles/new-york/form.json
> feat: form component examples & select item fallback

- apps/www/src/routes/examples/forms/profile-form.svelte
> docs: focus added input on form example

- apps/www/package.json
- apps/www/pnpm-lock.yaml
> chore: update bits

- apps/www/scripts/registry.ts
> fix: add paneforge to registry deps

- apps/www/src/lib/registry/default/ui/drawer/drawer-nested.svelte
- apps/www/src/lib/registry/default/ui/drawer/index.ts
- apps/www/src/lib/registry/new-york/ui/drawer/drawer-nested.svelte
- apps/www/src/lib/registry/new-york/ui/drawer/index.ts
This is the addition of nested drawers that already exist in vault https://github.com/huntabyte/vaul-svelte/blob/main/src/lib/vaul/components/nested-root.svelte
> feat: nested drawers

- README.md
> chore: add sponsors

- apps/www/src/routes/examples/mail/(components)/mail-display.svelte
- apps/www/src/routes/examples/mail/(components)/mail-list.svelte
- apps/www/src/routes/examples/mail/(components)/mail.svelte
Fixed mail list overflow--not being able to scroll to the very bottom of the list
https://github.com/huntabyte/shadcn-svelte/assets/53095479/225bbd74-6359-41ec-abd8-381141a24171
https://github.com/huntabyte/shadcn-svelte/assets/53095479/95f87da8-933c-4343-ba48-8ec656069d57
Fixed mail display overflow - when content overflows, can't scroll
https://github.com/huntabyte/shadcn-svelte/assets/53095479/f6913785-7dcd-469b-9359-e42b890f69a5
https://github.com/huntabyte/shadcn-svelte/assets/53095479/fcd1c21c-53be-4d65-9dd3-acadbc18d2c7
> docs: fix mail overflow

- .github/ISSUE_TEMPLATE/3-bug_report.yml
- .github/reproduire/needs-reproduction.md
- .github/workflows/reproduire-close.yml
- .github/workflows/reproduire.yml
> chore: add reproduire

- apps/www/src/content/cli.md
Closes https://github.com/huntabyte/shadcn-svelte/issues/804
> docs(style): add single update command line for consistency

- .changeset/config.json
> chore: Ignore playgrounds from changesets

- .github/workflows/docs-preview.yml
- .github/workflows/docs-production.yml
- apps/www/package.json
- apps/www/pnpm-lock.yaml
- apps/www/svelte.config.js
> chore: cloudflare

- apps/www/src/routes/+page.svelte
> chore: fix dark mail image

- apps/www/src/routes/examples/authentication/(components)/user-auth-form.svelte
The submission of the form is not working without the type="submit" attribute, as the type in <ButtonPrimitive.Root is explicitly set to type="button".
> fix: update user-auth-form.svelte

- package.json
- patches/@unovis__svelte@1.3.6-beta.0.patch
- pnpm-lock.yaml
> chore: Update `@unovis/svelte` and remove dependency patch

- README.md
> chore: update sponsor img

- apps/www/src/content/components/input.md
> docs: fixes Input Form example missing code preview

- apps/www/package.json
- pnpm-lock.yaml
> chore: update svelte radix

- apps/www/src/routes/(app)/blocks/+layout.svelte
> docs: update request block link

- apps/www/src/lib/registry/new-york/block/dashboard-03.svelte
> fix: typo in block placeholders

- .changeset/plenty-dogs-clean.md
- packages/cli/src/commands/init.ts
- packages/cli/src/utils/templates.ts
> feat: Adds TS support for tailwind config

- .changeset/rare-coats-try.md
- packages/cli/src/commands/update.ts
> fix: Update `utils` in its proper language mode

- packages/cli/src/commands/update.ts
> chore: Simplify logic

- apps/www/src/lib/registry/default/ui/input/input.svelte
- apps/www/src/lib/registry/default/ui/textarea/textarea.svelte
- apps/www/src/lib/registry/new-york/ui/input/input.svelte
- apps/www/src/lib/registry/new-york/ui/textarea/textarea.svelte
> fix: explicitly handle readonly for input / textarea

- apps/www/src/lib/registry/default/ui/input/index.ts
- apps/www/src/lib/registry/default/ui/input/input.svelte
- apps/www/src/lib/registry/new-york/ui/input/index.ts
- apps/www/src/lib/registry/new-york/ui/input/input.svelte
> feat: forward mouse wheel events on Input component

- apps/www/src/content/components/data-table.md
Fixed some documentation issues related to the datatable section.
- There was wrong code highlighting for some of the plugins
- Some of the code was outdated/didn't match with code shown before it
- Some explanations needed improving and some code needed explanations
Resolves #996
> docs(datatable): Improved and added some explanations

- README.md
> chore: update sponsors image

- apps/www/src/lib/components/docs/metadata.svelte
> chore: add plausible

- README.md
- apps/www/package.json
- pnpm-lock.yaml
> docs: update `bits-ui`

- .github/ISSUE_TEMPLATE/3-bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
> chore: update discord link in issue template

- .changeset/large-wolves-tease.md
- packages/cli/src/commands/init.ts
> chore: add overwrite notice for stylesheet and tailwind config

- packages/cli/src/utils/auto-detect.ts
> chore: add `globals` as a potential stylesheet

- apps/playground-js/reset.js
- apps/playground-ts/reset.js
> chore: cleanup playground script

- apps/www/src/content/components/data-table.md
- apps/www/src/lib/registry/default/example/cards/data-table.svelte
- apps/www/src/lib/registry/default/example/data-table-demo.svelte
- apps/www/src/lib/registry/new-york/example/cards/data-table.svelte
- apps/www/src/lib/registry/new-york/example/data-table-demo.svelte
- apps/www/src/routes/(app)/examples/data-table/data-table.svelte
- apps/www/src/routes/(app)/examples/tasks/(components)/data-table-pagination.svelte
> docs: pluginState.page is now pluginState.pagination

- apps/www/src/content/installation/manual.md
- apps/www/src/content/installation/sveltekit.md
- apps/www/src/content/installation/vite.md
addresses svelte-add changing command syntax and updates the docs to fix this
> docs: fix svelte-add command syntax

- apps/www/src/lib/registry/default/ui/input/index.ts
- apps/www/src/lib/registry/default/ui/input/input.svelte
- apps/www/src/lib/registry/new-york/ui/input/index.ts
- apps/www/src/lib/registry/new-york/ui/input/input.svelte
I needed to use this event but noticed is wasn't enabled in the custom `<Input />` component so I'm making this pr to enable it.
> feat: expose `mousemove` input event

- .changeset/weak-carrots-fry.md
- apps/www/src/content/cli.md
- packages/cli/src/utils/get-env-proxy.ts
> chore: slightly improve `env-proxy` and rephrase docs

- apps/www/src/content/components-json.md
added missing typescript option
> docs:(components-json)

- apps/www/src/content/cli.md
- apps/www/src/content/installation/index.md
Resubmitting, did these prs earlier online but deleted them accidentally, sorry about that, hopefully, this is ok now...
> docs: CLI & ESLint Config updates

- .prettierignore
gh actions broke and never ran the publish action. this pr is to trigger it again
> chore: trigger workflow

- apps/www/src/content/about.md
> docs: fix `vaul-svelte` link

- .changeset/mean-dancers-yawn.md
- packages/cli/src/utils/sveltekit.ts
> fix: use correct `cwd` when syncing SvelteKit projects

- sites/docs/src/content/installation/manual.md
- sites/docs/src/content/installation/sveltekit.md
- sites/docs/src/content/installation/vite.md
> docs: update `svelte-add` install command

- .github/workflows/build-preview.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-prod.yml
- package.json
> chore: Update deployment scripts

- .changeset/empty-clouds-deny.md
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/update.ts
- packages/cli/src/utils/auto-detect.ts
- packages/cli/src/utils/prompt-helpers.ts
> feat(PM): show working package manager

- sites/docs/src/routes/(app)/examples/forms/account/account-form.svelte
Fixes an issue with the schema/handling of the DOB in the account form.
> docs: fix Account form example

- sites/docs/src/lib/registry/default/ui/carousel/carousel.svelte
- sites/docs/src/lib/registry/new-york/ui/carousel/carousel.svelte
Follow-up to this report: https://github.com/huntabyte/shadcn-svelte/pull/1052#issuecomment-2373534907
Sorry I missed this as well. 🤦‍♂️
> fix: update selectedIndexStore when selecting an item

- sites/docs/src/routes/(app)/docs/+layout.server.ts
> chore: carbon take 2

- sites/docs/src/lib/components/docs/carbon.svelte
- sites/docs/src/lib/components/docs/table-of-contents.svelte
- sites/docs/src/routes/(app)/docs/+layout.server.ts
- sites/docs/src/routes/(app)/docs/+page.svelte
- sites/docs/src/routes/(app)/docs/[...slug]/+page.svelte
- sites/docs/svelte.config.js
> chore: carbon take 3

- sites/docs/src/lib/registry/default/ui/calendar/calendar-next-button.svelte
- sites/docs/src/lib/registry/new-york/ui/calendar/calendar-prev-button.svelte
Coincidentally, the last commit to these files was "my hand hurts". Sorry, HunterxHunter. 😅
> patch: correct calendar direction buttons

- sites/docs/src/lib/registry/new-york/ui/select/select-scroll-up-button.svelte
> fix: select scroll up button

- packages/cli/src/commands/add.ts
- pnpm-lock.yaml
> next: CLI tweaks

- pnpm-lock.yaml
- sites/docs/package.json
- sites/docs/src/lib/registry/default/ui/sheet/index.ts
- sites/docs/src/lib/registry/default/ui/sheet/sheet-content.svelte
- sites/docs/src/lib/registry/default/ui/sheet/sheet-overlay.svelte
- sites/docs/src/lib/registry/new-york/ui/sheet/index.ts
- sites/docs/src/lib/registry/new-york/ui/sheet/sheet-content.svelte
- sites/docs/src/lib/registry/new-york/ui/sheet/sheet-overlay.svelte
> next: fix sheet/update vaul-svelte

- sites/docs/src/__registry__/index.js
- sites/docs/src/lib/registry/default/example/date-picker-with-range.svelte
- sites/docs/src/lib/registry/new-york/example/date-picker-with-range.svelte
> fix: date range picker

- sites/docs/src/lib/components/docs/component-preview-manual.svelte
> next: mobile block previews

- sites/docs/src/lib/registry/default/example/cards/report-issue.svelte
- sites/docs/src/lib/registry/new-york/example/cards/report-issue.svelte
- sites/docs/src/routes/(app)/examples/cards/(components)/report-issue.svelte
> docs: fix select labels

- pnpm-lock.yaml
- sites/docs/package.json
> next: update bits

- sites/docs/src/lib/registry/default/example/calendar-with-selects.svelte
- sites/docs/src/lib/registry/new-york/example/calendar-with-selects.svelte
> docs: fix calendar with selects demo

- sites/docs/src/lib/registry/default/ui/scroll-area/scroll-area-scrollbar.svelte
- sites/docs/src/lib/registry/new-york/ui/scroll-area/scroll-area-scrollbar.svelte
- sites/docs/src/lib/registry/new-york/ui/scroll-area/scroll-area.svelte
> next: fix scroll area

- sites/docs/src/lib/registry/new-york/block/sidebar-01/+page.svelte
> docs: update import path for AppSidebar component

- sites/docs/src/content/components/select.md
> docs: Remove Select.Value in Select component

- pnpm-lock.yaml
- sites/docs/package.json
- sites/docs/src/content/components/command.md
- sites/docs/src/content/components/dropdown-menu.md
- sites/docs/src/lib/registry/default/ui/command/command-item.svelte
- sites/docs/src/lib/registry/default/ui/dropdown-menu/dropdown-menu-sub-trigger.svelte
- sites/docs/src/lib/registry/new-york/ui/command/command-item.svelte
- sites/docs/src/lib/registry/new-york/ui/dropdown-menu/dropdown-menu-sub-trigger.svelte
- sites/docs/src/routes/(app)/examples/forms/profile-form.svelte
- sites/docs/src/routes/(app)/examples/tasks/(components)/data-table-pagination.svelte
> next: tidy up docs

- sites/docs/src/content/components/sonner.md
I'm doing the 7GUIs tasks, ergo these patches for what I ran into🙂
> docs: highlight correct line in Sonner example

- sites/docs/src/content/components/data-table.md
- sites/docs/src/content/installation/manual.md
> docs: remove unused imports & correct attribute casing

- sites/docs/src/content/components/sidebar.md
Just add a . to </Sidebar.MenuBadge>
> docs: fix typo in sidebar.md

- sites/docs/src/lib/registry/new-york/ui/range-calendar/range-calendar-prev-button.svelte
> fix: range calendar button

- sites/docs/src/lib/registry/default/ui/tooltip/tooltip-content.svelte
- sites/docs/src/lib/registry/new-york/ui/tooltip/tooltip-content.svelte
- From [discord.](https://discord.com/channels/1194404141389336576/1194651836616032347/1301752793891082270)
- [Preview](https://e249f9d2.shadcn-svelte.pages.dev/docs/components/tooltip)
> patch: animate tooltips

- sites/docs/src/lib/registry/default/ui/table/table-footer.svelte
- sites/docs/src/lib/registry/new-york/ui/table/table-footer.svelte
> fix: footer displaying with inverted colors

- sites/docs/src/content/components/data-table.md
> docs: data table source link

- sites/docs/src/lib/registry/default/ui/switch/switch.svelte
- sites/docs/src/lib/registry/new-york/ui/switch/switch.svelte
> fix(next): Hardcoded pixel values on `<Switch/>`

- pnpm-lock.yaml
- sites/docs/package.json
Fixes #1464 
- Bumps bits-ui to latest
> chore(next): bump bits-ui

- sites/docs/src/lib/registry/default/ui/pagination/pagination-ellipsis.svelte
- sites/docs/src/lib/registry/new-york/ui/pagination/pagination-ellipsis.svelte
Fixes #1510
Did a quick search this is the only place I saw this issue in the project.
> fix: `aria-hidden` to `aria-hidden="true"` in `pagination-ellipsis`

- sites/docs/src/content/components/card.md
Fixes #1531 
Removes outdated docs for card.
> docs: Remove outdated card docs

- package.json
- pnpm-lock.yaml
> chore(ci): plz

- .github/workflows/deploy-prod.yml
> chore: ci dispatch deploy

- pnpm-lock.yaml
- sites/docs/package.json
- sites/docs/src/__registry__/index.js
- sites/docs/src/content/components/slider.md
- sites/docs/src/lib/registry/default/example/index.ts
- sites/docs/src/lib/registry/default/example/slider-demo.svelte
- sites/docs/src/lib/registry/default/example/slider-multiple.svelte
- sites/docs/src/lib/registry/default/ui/slider/slider.svelte
- sites/docs/src/lib/registry/new-york/example/index.ts
- sites/docs/src/lib/registry/new-york/example/slider-demo.svelte
- sites/docs/src/lib/registry/new-york/example/slider-multiple.svelte
- sites/docs/src/lib/registry/new-york/ui/slider/slider.svelte
- sites/docs/src/routes/(app)/examples/playground/(components)/max-length-selector.svelte
- sites/docs/src/routes/(app)/examples/playground/(components)/temperature-selector.svelte
- sites/docs/src/routes/(app)/examples/playground/(components)/top-p-selector.svelte
- sites/docs/src/routes/(app)/examples/playground/+page.svelte
See https://github.com/huntabyte/bits-ui/pull/1032 for more information.
> breaking: update bits slider for `single` and `multiple` types

- sites/docs/src/content/components/data-table.md
> docs: update data-table example code

- sites/docs/src/content/components/data-table.md
size-4 is already applied by Button and renderSnippet wasn't used in the code.
> fix: fixed imports and removed useless css

- pnpm-lock.yaml
- sites/docs/package.json
- sites/docs/scripts/tmp.ts
> next: bits 1.0

- sites/docs/src/content/installation/sveltekit.md
- sites/docs/src/content/installation/vite.md
> chore(next): Remove unnecessary install step in installation docs

- sites/docs/src/content/components/sidebar.md
Fixes a typo (this typo isn't present in https://ui.shadcn.com/docs/components/sidebar)
> docs(next): fix typo

- .gitignore
- sites/docs/scripts/build-registry.ts
- sites/docs/src/__registry__/index.js
- sites/docs/src/routes/(app)/colors/+page.svelte
- sites/docs/src/routes/(app)/themes/+page.svelte
- sites/docs/src/routes/registry/[...path]/+server.ts
This PR attempts to resolve the caching issues by utilizing API routes instead of relying on static assets for serving the latest and greatest registry tree/components.
> fix(next): registry caching issues

- .changeset/fair-beans-collect.md
- packages/cli/src/utils/registry/index.ts
Should help diagnose issues like #1745 
Now it properly bubbles the produced errors all the way up + it generates more specific error messages when fetching / parsing json responses.
> feat: improve error messages when fetching registry

- sites/docs/scripts/build-registry.ts
This could be done other ways but it works and now I can actually build the registry :)
> docs: make windows work

- pnpm-lock.yaml
- sites/docs/package.json
- sites/docs/src/lib/registry/default/example/calendar-with-selects.svelte
- sites/docs/src/lib/registry/new-york/example/calendar-with-selects.svelte
> docs: fix calendar with select examples

- .changeset/hot-weeks-spend.md
- packages/cli/package.json
- packages/cli/src/utils/registry/index.ts
Should help diagnose stuff like #1773
> feat(next): Improve error message when failing to fetch base colors from registry

- packages/cli/package.json
- packages/cli/src/utils/transformers.ts
- pnpm-lock.yaml
> chore(v4): Update to `@svecosystem/strip-types` 

- sites/docs/src/lib/registry/themes.ts
Fixes #1799  
- Updated `themes.ts` file 
- removed semicolon
> fix: typo in themes.ts (popover)

- sites/docs/src/lib/registry/ui/popover/index.ts
- sites/docs/src/lib/registry/ui/popover/popover-content.svelte
- sites/docs/src/lib/registry/ui/popover/popover-trigger.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-content.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-footer.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-group-action.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-group-content.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-group-label.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-group.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-header.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-input.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-inset.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-menu-action.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-menu-badge.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-menu-button.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-menu-item.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-menu-skeleton.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-menu-sub-button.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-menu-sub-item.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-menu-sub.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-menu.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-provider.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-rail.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-separator.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar-trigger.svelte
- sites/docs/src/lib/registry/ui/sidebar/sidebar.svelte
> chore: more tv4 styles

- pnpm-lock.yaml
- sites/docs/package.json
- sites/docs/src/lib/components/docs/theme-customizer/customizer.svelte
- sites/docs/src/lib/registry/ui/sonner/sonner.svelte
> chore(v4): upgrade `mode-watcher` to use the new runes version

- sites/docs/src/lib/components/docs/theme-customizer/customizer.svelte
- sites/docs/src/lib/registry/default/ui/sonner/sonner.svelte
- sites/docs/src/lib/registry/new-york/ui/sonner/sonner.svelte
> next: update mode watcher

- sites/docs/src/content/dark-mode/svelte.md
> docs: mode watcher css

- .changeset/spotty-insects-marry.md
- packages/cli/package.json
> chore(cli): remove `exports` and `main` fields

- packages/cli/package.json
same as #1843, but for the tailwind v4 branch
> chore(cli-tw4): remove `exports` and `main` fields

- pnpm-lock.yaml
- sites/docs/package.json
> chore: update mode watcher

- sites/docs/src/lib/registry/default/example/combobox-demo.svelte
- sites/docs/src/lib/registry/default/example/combobox-form.svelte
- sites/docs/src/lib/registry/default/ui/command/command-group.svelte
- sites/docs/src/lib/registry/new-york/example/combobox-demo.svelte
- sites/docs/src/lib/registry/new-york/example/combobox-form.svelte
- sites/docs/src/lib/registry/new-york/ui/command/command-group.svelte
Fixes an issue with the `Command.Group` needing a fallback value.
> fix: combobox

- .github/workflows/build-preview-tw-4.yml
- .github/workflows/deploy-preview-tw-4.yml
> add tailwind 4 workflows

- package.json
> chore: add v4 build script

- v4/src/lib/components/component-wrapper.svelte
- v4/src/lib/components/select-demo.svelte
> tw4: fix demo styles

- pnpm-lock.yaml
- sites/docs/package.json
- sites/docs/src/lib/components/docs/command-menu.svelte
> docs: fix search command

- sites/docs/src/content/components/data-table.md
> chore: add data getter and `onPaginationChange` to Step 2 on `data-table.md`

- v4/src/lib/components/app-sidebar.svelte
- v4/src/lib/components/range-calendar-demo.svelte
- v4/src/lib/registry/charts/chart-bar-active.svelte
- v4/src/lib/registry/charts/chart-line-dots-colors.svelte
- v4/src/lib/registry/charts/chart-pie-label-custom.svelte
- v4/src/routes/(app)/+page.svelte
- v4/src/routes/(app)/charts/+page.svelte
- v4/src/routes/(app)/charts/charts.ts
> tw4: tweaks

- sites/docs/src/app.html
- sites/docs/src/lib/components/docs/command-menu.svelte
- sites/docs/src/lib/components/docs/component-preview.svelte
- sites/docs/src/lib/components/docs/doc-tabs/doc-tabs-content.svelte
- sites/docs/src/lib/components/docs/doc-tabs/doc-tabs-list.svelte
- sites/docs/src/lib/components/docs/doc-tabs/doc-tabs-trigger.svelte
- sites/docs/src/lib/components/docs/doc-tabs/index.ts
- sites/docs/src/lib/components/docs/docs-nav/docs-nav-items.svelte
- sites/docs/src/lib/components/docs/docs-nav/docs-nav.svelte
- sites/docs/src/lib/components/docs/install-tabs.svelte
- sites/docs/src/lib/components/docs/nav/main-nav.svelte
- sites/docs/src/lib/components/docs/page-header/page-header-actions.svelte
- sites/docs/src/lib/components/docs/page-header/page-header-description.svelte
- sites/docs/src/lib/components/docs/page-header/page-header-heading.svelte
- sites/docs/src/lib/components/docs/page-header/page-header.svelte
- sites/docs/src/lib/components/docs/site-footer.svelte
- sites/docs/src/lib/components/docs/site-header.svelte
- sites/docs/src/lib/config/docs.ts
- sites/docs/src/routes/(app)/+layout.svelte
- sites/docs/src/routes/(app)/+page.svelte
- sites/docs/src/routes/(app)/docs/+layout.svelte
- sites/docs/src/routes/(app)/docs/+page.svelte
- sites/docs/src/routes/(app)/docs/[...slug]/+page.svelte
- sites/docs/src/routes/+layout.svelte
- sites/docs/src/styles/globals.css
- sites/docs/src/styles/markdown.css
> docs(tw4): update doc styles

- .github/workflows/deploy-tailwind-3.yml
> chore: workflows

- packages/cli/src/commands/registry/build.ts
- packages/cli/src/constants.ts
- packages/cli/src/utils/transformers.ts
- packages/cli/test/utils/transformers.spec.ts
- packages/registry/src/schemas.ts
- sites/docs/registry-default.json
- sites/docs/registry-new-york.json
- sites/docs/scripts/build-registry.ts
Follow-up to #1896
The `check` failure is unrelated to the PR
> feat(tw3-next): transform registry aliases into alias placeholders

- sites/docs/src/lib/registry/blocks/login-01/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-01/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-01/components/app-sidebar.svelte
- sites/docs/src/lib/registry/blocks/sidebar-02/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-02/components/app-sidebar.svelte
- sites/docs/src/lib/registry/blocks/sidebar-03/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-04/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-05/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-05/components/app-sidebar.svelte
- sites/docs/src/lib/registry/blocks/sidebar-06/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-06/components/app-sidebar.svelte
- sites/docs/src/lib/registry/blocks/sidebar-07/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-07/components/app-sidebar.svelte
- sites/docs/src/lib/registry/blocks/sidebar-08/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-08/components/app-sidebar.svelte
- sites/docs/src/lib/registry/blocks/sidebar-09/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-09/components/app-sidebar.svelte
- sites/docs/src/lib/registry/blocks/sidebar-10/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-10/components/app-sidebar.svelte
- sites/docs/src/lib/registry/blocks/sidebar-11/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-12/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-12/components/app-sidebar.svelte
- sites/docs/src/lib/registry/blocks/sidebar-13/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-14/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-15/+page.svelte
- sites/docs/src/lib/registry/blocks/sidebar-15/components/sidebar-left.svelte
- sites/docs/src/lib/registry/blocks/sidebar-15/components/sidebar-right.svelte
> fix(tw4-next): use relative component imports in blocks

- pnpm-lock.yaml
- sites/docs/package.json
- sites/docs/src/lib/registry/examples/dropdown-menu-demo.svelte
- sites/docs/src/lib/registry/ui/context-menu/context-menu-sub-trigger.svelte
- sites/docs/src/lib/registry/ui/dropdown-menu/dropdown-menu-item.svelte
- sites/docs/src/lib/registry/ui/dropdown-menu/dropdown-menu-sub-trigger.svelte
- sites/docs/src/lib/registry/ui/sonner/sonner.svelte
- v4/src/lib/registry/ui/menubar/menubar-sub-trigger.svelte
> tw4: style and sonner update

- .github/FUNDING.yml
You should consider sponsoring https://github.com/adriangonz97 😃
> chore: add cokakoala to funding

- .changeset/yellow-oranges-invite.md
- packages/cli/src/commands/add/index.ts
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/update/index.ts
- packages/cli/src/utils/install-deps.ts
- packages/cli/src/utils/prompt-helpers.ts
- packages/cli/test/commands/init.test.ts
> chore(cli): add `taskLog` to dependency installs

- .github/workflows/build-preview-tw-4.yml
Removes the pin from the `next-tailwind-4` branch and deploys when changes to `next`
> chore: adjust tailwind 4 demo workflow

- .changeset/wicked-terms-give.md
- packages/cli/src/commands/add/preflight.ts
- packages/cli/src/commands/init/preflight.ts
- packages/cli/src/commands/registry/deps-resolver.ts
- packages/cli/src/utils/utils.ts
- packages/cli/test/utils/preflight-add.test.ts
- packages/cli/test/utils/preflight-init.test.ts
> fix(cli): resolve deps from node_modules when evaluating their versions

- .changeset/smooth-candies-shake.md
- packages/cli/src/commands/add/index.ts
- packages/cli/src/commands/init/index.ts
- packages/cli/src/utils/prompt-helpers.ts
> fix(cli): remove dangling comma in "components to install" list

- sites/docs/package.json
- sites/docs/src/__registry__/index.js
- sites/docs/src/lib/components/docs/carbon.svelte
- sites/docs/src/lib/components/docs/nav/mobile-nav.svelte
- sites/docs/src/lib/components/docs/site-header.svelte
- sites/docs/src/lib/registry/examples/sheet-demo.svelte
- sites/docs/src/lib/registry/examples/sheet-side.svelte
- sites/docs/src/lib/registry/ui/sheet/sheet-content.svelte
- v4/src/lib/registry/examples/sheet-demo.svelte
- v4/src/lib/registry/examples/sheet-side.svelte
- v4/src/lib/registry/ui/sheet/sheet-content.svelte
> fix(Sheet): styles

- sites/docs/src/lib/components/docs/nav/mobile-nav.svelte
> docs: some nav padding

- sites/docs/src/lib/registry/ui/input/input.svelte
> fix: add lost data slot in input component

- sites/docs/src/lib/registry/ui/select/select-scroll-down-button.svelte
- sites/docs/src/lib/registry/ui/select/select-scroll-up-button.svelte
> fix(next): Select scroll button slots

- sites/docs/src/lib/registry/ui/checkbox/checkbox.svelte
- sites/docs/src/lib/registry/ui/table/table-cell.svelte
- sites/docs/src/lib/registry/ui/table/table-head.svelte
- sites/docs/src/routes/(app)/examples/tasks/components/data-table.svelte
- v4/src/lib/registry/ui/checkbox/checkbox.svelte
- v4/src/lib/registry/ui/table/table-cell.svelte
- v4/src/lib/registry/ui/table/table-head.svelte
Fixes #1947 
Fix via https://github.com/shadcn-ui/ui/pull/7419
Before:
After:
> fix: misaligned and jumpy table checkboxes

- sites/docs/src/content/installation/astro.md
> docs(next): Add correct paths to astro install docs

- .github/workflows/build-preview-tw-4.yml
- .github/workflows/build-preview.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-tailwind-3.yml
- .github/workflows/release.yml
- .github/workflows/reproduire-close.yml
Remove unnecessary things, speed up installs by freezing lockfile and preferring offline 😃
> chore: update workflows

- pnpm-lock.yaml
- sites/docs/package.json
- sites/docs/registry.json
> fix: update `layerchart` for proper tooltip rendering

- sites/docs/src/routes/(app)/blocks/+layout.svelte
> docs: update description

- .changeset/thin-pens-tie.md
- packages/cli/src/utils/transformers.ts
> fix: disable ES transformations when stripping types

- .changeset/metal-streets-argue.md
- packages/cli/src/utils/registry/index.ts
- packages/cli/test/utils/registry.test.ts
> fix(cli-next): respect the `utils` path-alias

- sites/docs/src/lib/registry/ui/data-table/flex-render.svelte
- sites/docs/src/lib/registry/ui/form/form-element-field.svelte
- sites/docs/src/lib/registry/ui/form/form-field.svelte
- sites/docs/src/lib/registry/ui/form/form-fieldset.svelte
- sites/docs/src/routes/(app)/examples/tasks/components/data-table-faceted-filter.svelte
- sites/docs/src/routes/(app)/examples/tasks/components/data-table-toolbar.svelte
- sites/docs/src/routes/(app)/examples/tasks/components/data-table-view-options.svelte
- v4/src/lib/registry/ui/data-table/flex-render.svelte
- v4/src/lib/registry/ui/form/form-element-field.svelte
- v4/src/lib/registry/ui/form/form-field.svelte
- v4/src/lib/registry/ui/form/form-fieldset.svelte
closes #1607
This doesn't look to be necessary any more!
> fix: remove types in `module` scripts

- sites/docs/package.json
- sites/docs/src/routes/(app)/examples/mail/(components)/mail-display.svelte
> fix: Mail calendar example

- .github/workflows/autoformat.yml
> chore: autoformat workflow

- pnpm-lock.yaml
- v4/package.json
- v4/src/lib/registry/examples/drawer-demo.svelte
- v4/src/lib/registry/ui/chart/chart-container.svelte
> chore: remove unovis

- sites/docs/src/content/migration/tailwind-v4.md
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/acee7eb7-35a4-4693-9ac7-0a7e7d48e81e) | ![image](https://github.com/user-attachments/assets/e7e37f9c-8335-468e-90b4-671ca3da5ada) |
> docs: Remove duplicate heading number in `/docs/migration/tailwind-v4`

- docs/src/lib/registry/blocks/chart-area-interactive.svelte
- docs/src/routes/(app)/examples/dashboard/components/chart-area-interactive.svelte
> next: chart clip

- .changeset/pre.json
> chore(cli): exit prerelease

- docs/content/changelog.md
- docs/content/components/calendar.md
- docs/content/components/range-calendar.md
- docs/src/routes/(app)/blocks/+layout.svelte
> docs: fix calendar blocks link

- docs/src/lib/components/theme-customizer.svelte
- docs/src/lib/user-config.svelte.ts
- registry-template/src/lib/registry/ui/input/input.svelte
- registry-template/src/lib/registry/ui/label/label.svelte
- registry-template/src/lib/registry/ui/textarea/input.svelte
> docs: ensure all themes are in schema

- docs/src/lib/components/component-preview.svelte
- docs/src/routes/(app)/blocks/[category]/+page.svelte
- docs/src/routes/(app)/blocks/[category]/+page.ts
- registry-template/src/lib/registry/ui/card/card-footer.svelte
- registry-template/src/lib/registry/ui/card/card-header.svelte
- registry-template/src/lib/registry/ui/card/card-title.svelte
- registry-template/src/lib/registry/ui/input/input.svelte
- registry-template/src/lib/registry/ui/label/label.svelte
- registry-template/src/lib/registry/ui/textarea/input.svelte
> docs: ensure calendar blocks render on mobile

- docs/src/lib/components/ethical.svelte
- docs/src/routes/(app)/docs/[...slug]/+page.svelte
> chore: carbon to ethical

- .github/workflows/deploy-prod.yml
> chore: increase runner memory during build

- .github/workflows/deploy-prod.yml
- docs/vite.config.ts
> docs: add workflow dispatch

- docs/src/app.html
- docs/src/lib/components/ethical.svelte
> docs: update ethical

- docs/src/lib/components/github-link.svelte
- docs/src/lib/constants.ts
- docs/src/routes/(app)/+layout.server.ts
- docs/src/routes/(app)/+layout.ts
> docs: better star count

- docs/content/registry/getting-started.md
- docs/content/registry/index.md
Fixed wrong registry template links in docs.
> docs: change wrong registry template links

- docs/package.json
- docs/registry.json
- docs/scripts/build-registry.ts
- pnpm-lock.yaml
> chore: update deps

- CONTRIBUTING.md
> chore: update contrib guide

- docs/content/migration/tailwind-v4.md
> fix: Correct link to Svelte 5 migration guide

- .changeset/light-eggs-drive.md
- packages/registry/package.json
> chore: release registry package

- sites/docs/src/lib/components/docs/svelte-5-banner.svelte
Updated link & text now that Svelte 5 docs are out of preview
> fix: Svelte 5 banner

- docs/src/lib/registry/ui/dropdown-menu/dropdown-menu-content.svelte
> fix: Remove outline for dropdown menu content

- docs/src/lib/registry/ui/command/command-input.svelte
> fix: close button obscured when command input string too long

- .changeset/eighty-planets-hunt.md
- packages/cli/src/utils/add-registry-items.ts
- packages/cli/test/utils/add-registry-items.test.ts
> fix(cli): external registry overwrites

- .github/workflows/ci.yml
- docs/src/lib/components/cards/notion-prompt-form.svelte
- pnpm-lock.yaml
Was missing usage of the `child` snippet resulting in some bad formatting of the menu.
> fix: notion prompt form demo

- docs/src/lib/registry/examples/empty-avatar-demo.svelte
- docs/src/lib/registry/examples/empty-avatar-group-demo.svelte
- docs/src/lib/registry/examples/empty-background-demo.svelte
- docs/src/lib/registry/examples/empty-demo.svelte
- docs/src/lib/registry/examples/empty-outline-demo.svelte
- docs/src/lib/registry/ui/form/form-button.svelte
> fix: button usage in empty examples
